### ISSUE TITLE
[BUG] Masa's Mod hotkey doesn't work after entering the game

### ISSUE THREAD

**Issue by Hygyubu** [PojavLauncherTeam/PojavLauncher#1001]
### Describe the bug
after the version3.3.1,Masa's Mod(such as tweakeroo,litematica) hotkey doesn't work after starting the world

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2.start minecraft1.16.5(mod api :fabric）
3.enter the world
4.At first, hotkeys can still be used. After a while, they won't work

**Platform:**
 - Device Model [Huawei AGS2-W09 4/64]
 - CPU architecture [ aarch64] 
 - Android Version [ 9]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
Fill the template

**Comment by khanhduytran0** [comment]
@Hygyubu

**Comment by Zelioz273** [comment]
Finally someone has the same issue i had. I made a bug report on this too a little while ago. Try going into the game and use the hotkey to see it still works, press any slot on your hotbar, and try the hotkey again. For me, this happens because something changing when you try pressing the hotbar. Weird way to fix it but it fixes when i switched between two slots quickly by pressing 1 button that switched to any slot and another button that switched to a different slot. Just don't press the hotbar again because it messes up again.

**Comment by andogy** [comment]
just minimum the minecraft window and reopen it, simple!
