### ISSUE TITLE
[F-REQ] It is recommended to add a modifiable screen safe area

### ISSUE THREAD

**Issue by PTALTS-LK** [PojavLauncherTeam/PojavLauncher#1088]
**Is your feature request related to a problem? Please describe.**
On some mobile phones, the rounded corners of the camera and screen will obscure some of the picture

**Describe the solution you'd like**
Add an adjustable screen safe area screen like BE Mimecraft, it is recommended to change to left and right adjustable

**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by khanhduytran0** [comment]
Minecraft Java does not support safe area.

**Comment by khanhduytran0** [comment]
Alternatively, you can take a look at "Ignore notch" option.

**Comment by CPXMC** [comment]
> Minecraft Java does not support safe area.

Can this be solved at the software level

It seems that the old pojav does not have this problem, it may be because there is no support for full screen

> Minecraft Java does not support safe area.

Can this be solved at the software level

It seems that the old pojav does not have this problem, it may be because there is no support for full screen

**Comment by PTALTS-LK** [comment]
> Minecraft Java does not support safe area.

Can this be solved at the software level

It seems that the old pojav does not have this problem, it may be because there is no support for full screen
