### ISSUE TITLE
[F-REQ]lunar client and I suggest to made a appimage mod installer 

### ISSUE THREAD

**Issue by notpvpking** [PojavLauncherTeam/PojavLauncher#1140]
If pojav team add appimage Minecraft mod installer all player get all client they wanted , request issue will help to defeat mcinabox launcher.......

**Comment by notpvpking** [comment]
Ummm I have write the comment at wrong place hahahaahhaah

**Comment by CriticalRange** [comment]
Wdym defeat MCinaBox launcher ? It's already discontinued, just somehow more popular than pojav even when pojav is in google play, also no idea about appimage

**Comment by notpvpking** [comment]
Appimage were Linux installer.

**Comment by khanhduytran0** [comment]
But Android is banning executables and appimage might uses a linker which will force us to provide the entirely Linux environment just to install a thing.

**Comment by ebuild-1** [comment]
I did some quick research from GitHub and found out that **"MCinabox"** is discontinued.
And I don't think MCinabox laucher is popular, the first version was Chinese so it didn't really attract mobile users. It gained popularity because of YouTubers bringing steps or when they launched the English version. **It's already defeated by features, but not in popularity.**
