### ISSUE TITLE
[BUG] <No se puede jugar Minecraft 1.16>

### ISSUE THREAD

**Issue by MRY20** [PojavLauncherTeam/PojavLauncher#1631]
Cuando entré en Pojavlauncher y jugué 1.16, el juego no se pudo abrir y regresó a la pantalla de inicio de sesión.

**Comment by khanhduytran0** [comment]
English please, we don't understand your language @MRY20

**Comment by khanhduytran0** [comment]
Invalid session? Have you logged in with paid account?

**Comment by khanhduytran0** [comment]
Also, fill the template.

**Comment by MRY20** [comment]
> ¿Sesión inválida? ¿Ha iniciado sesión con una cuenta de pago?

Tengo una cuenta sin conexión y no puedo jugar.

**Comment by khanhduytran0** [comment]
So, you expect to play on Hypixel with an offline account?

**Comment by khanhduytran0** [comment]
~~oh lol~~
~~**English please**~~ if possible

**Comment by khanhduytran0** [comment]
> Also, fill the template.

**Comment by khanhduytran0** [comment]
or this will be closed. we didn't know anything about the crash!

**Comment by khanhduytran0** [comment]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
A clear and concise description of what the bug is.

**Add a log file if you want to see your bug fixed !**

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]


<details> <summary><b>Additional context</b></summary>
<br>
<pre>
Add any other context about the problem here.
</pre>
</details>
