### ISSUE TITLE
What are the Uses Of Different Renderers ?

### ISSUE THREAD

**Issue by Future-spec** [PojavLauncherTeam/PojavLauncher#1660]
Well, While Browsing some Settings In Pojavlauncher ........ I saw an Option in Renderer , I Tried and My Device Can Run All 4 of it. I Just Want To Know , Which I would Be Right For Me....... Also Ensuring That It will Give Me Perfect Graphics And Performance......

**Comment by mchnjt** [comment]
gl4es 1.1.4 is the default renderer, while gl4es 1.1.5 (either converted to OpenGL 2 or 3) is the color fix for 1.14 and above, and it is also used for 1.17 with the shader fix (it's bugged for 1.14 and below). Meanwhile, Zink (vulkan) exports to OpenGL 4, and it is really, really laggy so that the devs is considering it to 'no-support'. You can use it for 1.17 without the shader fix which enables 1.17 to render while using gl4es 1.1.5.
(still idk if these are facts but i'm sure they are)

**Comment by Future-spec** [comment]
Thanks , But Can Anyone Give Me Certain Answer as I am Using 4GB Ram Tablet, Which Would Be Perfect For Me ?

**Comment by Future-spec** [comment]
I Want The Name Of The Renderer........

**Comment by khanhduytran0** [comment]
There's no certain renderer, as what he said, depending on certain Minecraft versions, you have to use certain renderers
- 1.12.2 and older: gl4es 1.1.4
- 1.13 to 1.14.x: gl4es 1.1.4 or zink
- 1.15+: gl4es 1.1.5 (OpenGL ES 2/3) or zink

**Comment by oakely2** [comment]
Use Gl4es 1.1.4 if you play 1.15 below
Use Gl4es 1.1.5 if you play 1.16 up

theres nothing to do about ram

**Comment by Future-spec** [comment]
OK, Thank You A Lot..........
