### ISSUE TITLE
[F-REQ]Many Mod like AOA3 Immersive EngineeringThis blurring problem can only be solved with the zink renderer, but this renderer is very stuck, will it be optimized later or will other renderers be added 

### ISSUE THREAD

**Issue by yx-storehouse** [PojavLauncherTeam/PojavLauncher#1698]
![Screenshot_2021-07-19-19-29-50-461_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/87650007/126158938-94230c10-53d0-4448-997d-d9f8b2c30523.jpg)
I hope to enhance the frame rate of the zink renderer

**Comment by doubijunNB** [comment]
me too

**Comment by khanhduytran0** [comment]
1. Fill the template.
2. Phone is not a PC, but Minecraft Java is a PC game. Mobile device can't run anything that PC can, it will not smooth if your device is slow.
3. Zink is laggy as h3ll, we didn't "make" Zink, but **ported it** to mobile platform. So we can't do anything. ~~If you have worked on Nvidia, go and contribute to Zink~~
4. We don't provide any new renderer since we are not graphics nor OpenGL developer. We may once RTX 3090 can be inserted into your phone.
