### ISSUE TITLE
Minecraft 1.17 optifine is playable now With lag?

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#1751]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by khanhduytran0** [comment]
@kedrick021
Did you even fill the template?
Did you even search for older issues?
What's the point of playing Optifine 1.17 with Zink while it's even slower than vanilla with gl4es?

**Comment by kedrick021** [comment]
So I can't thank for replying I wait more and soon can playable optifine 1.17 coming soon

**Comment by khanhduytran0** [comment]
It may not gonna be soon just like asking for "when will SEUS PTGI E12 work". We have more things to do than making every 1.17 mod to works.

**Comment by khanhduytran0** [comment]
If you have GLSL, Java and C++ knowledge, *do it yourself*. ~~you may want to keep an eye at [VGPU project](https://github.com/luo9674/VGPU)~~

**Comment by khanhduytran0** [comment]
We don't work at Nvidia, so porting PC shaders to mobile isn't just done in one day. Yes, OptiFine 1.17.x has their built-in shaders to optimize the game, **which are never designed for mobile**, especially since 1.17 uses OpenGL 3.2, OptiFine and many of mods that support 1.17.x starting to do the same thing. If your phone has OpenGL ES 3.2, understand this: OpenGL ≠ OpenGL ES.

**Comment by WesleyVanNeck** [comment]
1.17 available soon tm

**Comment by WesleyVanNeck** [comment]
https://github.com/luo9674/VGPU/releases/tag/v1.2.2-beta

**Comment by kedrick021** [comment]
> https://github.com/luo9674/VGPU/releases/tag/v1.2.2-beta

This gonna be fix lag on optifine?

**Comment by Vghggggjgjb** [comment]
@LegacyGamerHD []()_8н90_
