### ISSUE TITLE
Remove the Skip Download button

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#1935]
### Is this request related to a bug?

No

### Describe the request.

Remove the Skip Download option because you can easily misclick it and have to start over.

### Anything else?

No

**Comment by NotAHero04** [comment]
The developers were aware of removing the ‘Skip’ button. Anyway, thanks for suggesting.

**Comment by pojavluncher2021** [comment]
No, Let it be on its own, So that you don't have to wait a long time.

**Comment by pojavluncher2021** [comment]
Close this issue.

**Comment by khanhduytran0** [comment]
> No, Let it be on its own, So that you don't have to wait a long time.

Nah, multithread download has been implemented already, so downloading the whole assets pack is done in just 1 minute.

**Comment by Mathias-Boulay** [comment]
I still want to remove this button but some people are opposed to this change

**Comment by yxles-dev** [comment]
God pls delete the button the last time I tried downloading 1.16 I thought my phone went coo-coo crazy and the GPU isn't compatible with the app since the skybox on the menu only showed up as gray but it turns out that I mistouched the button and only need to complete downloading the files for it to go back to normal

**Comment by ghost** [comment]
> ### Is this request related to a bug?
> 
> No
> 
> ### Describe the request.
> 
> Remove the Skip Download option because you can easily misclick it and have to start over.
> 
> ### Anything else?
> 
> No

Nah. close this issue

**Comment by Ganxyfrommc** [comment]
Hey why u download 1.16 and Its 16 MB so i uninstall pojav and download it again and 317 MB  don't know because i leave the handphone so not know Its fully download but background Is just white and of i play forge they crash and redownload the 1.16 but ITS not work. Why Is because openjdk V3 or v3.1.1 because i never gets this  igets this in 1 week ago because i uninstall pojav because i uninstall the jvms so i cut the forge 1.16.5 to another file and i remove the pojav files and not know i have to have 1.16.5 to play forge 1.16.5 and i download 1.16.5 and Its just 16 and 17 mb i mean the jar 16  MB because the real Is 317

**Comment by only-surviv-cre-cant-need-save-worlds** [comment]
Dont remove, add a setting to hide that button

**Comment by mchnjt** [comment]
Remove it lol

**Comment by Mathias-Boulay** [comment]
THIS WILL BE DONE ON RELEASE ONLY BUILDS
