### ISSUE TITLE
Java 8 

### ISSUE THREAD

**Issue by ajit850** [PojavLauncherTeam/PojavLauncher#2082]
### Is this request related to a bug?

No,we can use Java 8 jre to play Minecraft 1.17+

### Describe the request.

There is no need of JDK 17 to run 1.17+.

**Comment by ajit850** [comment]
https://youtu.be/3LluIY3wr1k

**Comment by khanhduytran0** [comment]
~~Proof is not given~~ wait, also even **vanilla 1.17.x** was able to run with just java 8, what about OptiFine, Forge and Fabric mods?

> JDK 17

Also, why are you talking about **J**ava **D**evelopment **K**it instead of **J**ava **<ins>Runtime</ins>** **E**nvironment (JRE)? are you recompiling Minecraft java in PojavLauncher from decompiled source?

**Comment by khanhduytran0** [comment]
looks like you didn’t even read the log, that’s how per-version-config works
![0FF30D0D-866A-4922-B80A-4E0208CFCAD7](https://user-images.githubusercontent.com/40482367/135594417-9578bd3f-d15e-495f-bfe1-25d0512febd6.jpeg)
