### ISSUE TITLE
[BUG] Hypixel not working

### ISSUE THREAD

**Issue by Noahgamez2009** [PojavLauncherTeam/PojavLauncher#2124]
### Describe the bug

so everytime I add Hypixel it says:      Failed to login: Invalid session  {Try restarting your game}
so I dont know why it does this but just please tell me why its not working or fix it.

### The log file and images/videos

![Screenshot 2021-10-15 10 51 34 PM](https://user-images.githubusercontent.com/84477315/137570914-b7530cd8-68b9-4377-a9f5-6d84d3c1facb.png)

### Steps To Reproduce

```markdown
I dont know?
```

### Expected Behavior

I wish this would work.

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by Yashjbk17** [comment]
See pojav launcher is a creacked launcher so you can't play on primium servers you can only play if you have a primium account

**Comment by Yashjbk17** [comment]
You can play on creaked servers

**Comment by Noahgamez2009** [comment]
whats that mean?

**Comment by mchnjt** [comment]
> whats that mean?

PojavLauncher's Minecraft versions are free to download, as same as TLauncher. Though, PojavLauncher doesn't violate the EULA, as it's download server is on the official server, and the contents are not modified. In the future, this "cracked" thing will be removed.

In order to play "Hypickle", all you need to do is to sign in a Microsoft account **with Minecraft bought in it.**

Also, don't forget to sign it out on the/any PC Minecraft launcher, as it may cause **"token does not exist"**.
