### ISSUE TITLE
where is the .minecraft folder?

### ISSUE THREAD

**Issue by IranDoGrauUuL** [PojavLauncherTeam/PojavLauncher#2230]
### Describe the bug

my phone is an android 10, and i want to play minecraft with mods and install a datapack but the .minecraft folder does not appear, i am using the playstore version, what should i do? please help me

### The log file and images/videos

.

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

the .minecraft folder was supposed to be in games/pojavlauncher/

### Platform

```markdown
- Device model: xiaomi redmi 9A / 22g
- CPU architecture: aarch32 
- Android version: 10
- PojavLauncher version: playstore
```

**Comment by ghost** [comment]
Due to Google's new scoped storage enforcements added in Android 10 and higher, we are required to move the game directory into an app-private folder.
You can find the new location of the folders in sdcard/Android/data/net.kdt.pojavlaunch/files/ (don't forget to enable "Show hidden folders" in the file manager).

**Comment by IranDoGrauUuL** [comment]
man, thank you so much, you really helped me, have a nice day, and I'm sorry if I bothered you
