### ISSUE TITLE
[BUG] bugs and bugs

### ISSUE THREAD

**Issue by moha0116** [PojavLauncherTeam/PojavLauncher#2247]
### Describe the bug

i have some bugs

> 1.i can't use all of rams my device have 2 gb ram i can use 1100 mb if i use 1100 or 1000 or 900 mb game crash.

> 2.i can't playing in 1.17+ and make crash even though i followed all steps.

> 3.i can't playing forge of any version app colosed if i entered in any world

> 4.1.13+ make crash and app exiting

### The log file and images/videos

*

### Steps To Reproduce

```markdown
i can't playing correctly
```

### Expected Behavior

*

### Platform

```markdown
- Device model: X96Q 2gb ram 16 gb storage
- CPU architecture: arm
- Android version: 10
- PojavLauncher version: lasted release
```

### Anything else?

please fix this bugs

**Comment by khanhduytran0** [comment]
You have some more bugs:
- Expected behavior is invalid.
- `Steps to reproduce` is incomplete.
- "lasted release" is an invalid version name.
- Problem 1: 32bit limit. Switch to a 64bit device.
- Problem 2: Currently there’s no 1.17+ support for 32bit. Switch to a 64bit device.
- Problem 3 and 4: latestlog.txt is not attached (field `The log file and images/videos` is invalid).

**Comment by khanhduytran0** [comment]
If these (except switching to 64bit) are not resolved in 24 hours, this issue will be closed as invalid.

**Comment by moha0116** [comment]
my old phone are 64 bits ,i don't have in these phone some of this problems

**Comment by moha0116** [comment]
i play labymod 1.12.2

**Comment by khanhduytran0** [comment]
> You have some more bugs:
> 
> * Expected behavior is invalid.
> * `Steps to reproduce` is incomplete.
> * "lasted release" is an invalid version name.
> * Problem 3 and 4: latestlog.txt is not attached (field `The log file and images/videos` is invalid).

Closing as these aren’t filled.
