### ISSUE TITLE
[BUG] Xbox Game Pass not working

### ISSUE THREAD

**Issue by mar4ello6** [PojavLauncherTeam/PojavLauncher#2265]
### Describe the bug

When you try to play Minecraft in PojavLauncher with Xbox Game Pass you get error 404.

### The log file and images/videos

![Screenshot_2021-11-21-13-53-24-886_net kdt pojavlaunch](https://user-images.githubusercontent.com/44264356/142761002-68b5b668-1ce7-489e-9e4c-7ccef0377a08.jpg)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Login Microsoft account with Xbox Game Pass on it
3. Get error
```

### Expected Behavior

I expect launcher to let me in.

### Platform

```markdown
- Device model: Mi 10T Pro 8/128G
- CPU architecture: ARMv8, I guess???
- Android version: 11
- PojavLauncher version: Latest in Google Play
```

### Anything else?

If you launch Minecraft Launcher on PC first, then you can enter your account and play in PojavLauncher.

**Comment by WesleyVanNeck** [comment]
use the xbox one

**Comment by Mathias-Boulay** [comment]
I feel like this will take some time before Microsoft provides something to deal with that

**Comment by SprainedSpark89** [comment]
You don't need to have game pass but maybe it will not work until you buy java edition try this on a pc download minecraft https://www.minecraft.net/en-us/download then use your microsoft account try a pc without microsoft store or try to use it with microsoft store not logged in if it works on the pc with microsoft store not logged in check the store it maybe logged in i can't test this because i don't have a pc.

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build

**Comment by gfvgfvytv** [comment]
[Uploading latestlog.txt…]()
