### ISSUE TITLE
[F-Req] Editing the .minecraft folder directly

### ISSUE THREAD

**Issue by Errorbot1122** [PojavLauncherTeam/PojavLauncher#2268]
### Is this request related to a bug?

No, but I want to be able to change the display name of a user so I can do this:

EDIT: Yes it does relate to all the problems with LAN servers, and how that won't work with the app...

https://gaming.stackexchange.com/questions/148409/can-two-users-play-on-a-minecraft-server-using-the-same-account

### Describe the request.

Being able to edit the files of the launcher, just like you can in pc

### Anything else?

idk yet...

**Comment by artdeell** [comment]
Profiles were already a thing on the profiles branch, but they won't help you here, since Pojav is very much static and wasn't really supposed to run 2 Minecrafts at the same time

**Comment by Errorbot1122** [comment]
@artdeell ???, I'm not trying to run 2 Minecraft... I'm trying to edit the `.minecraft` folder

**Comment by dachisao** [comment]
Did you mean, you wanna rename the minecraft folder to something else?

**Comment by ghost** [comment]
hmm if his mean that he wants to rename the minecraft folder so he shouldn't do that tho

**Comment by Errorbot1122** [comment]
no @retroXolotl i want the edit the files in it

**Comment by ghost** [comment]
so if you want to edit the files in it you must have some app that can edit them then

**Comment by khanhduytran0** [comment]
> Being able to edit the files of the launcher, just like you can in pc

<ins>Text editor exists for a reason</ins>. Can you just walk into it then edit? 

> but I want to be able to change the display name of a user so I can do this

Pojav doesn’t use `launcher_profiles.json` for storing authentication stuff, it is considered as risky as it stands in a public place on Android 9 and older.

- If you use a local server instead of LAN then look at the tutorial:
> - Edit server.properties found in the parent folder of your minecraft folder.
> - Find and update online-mode=false

So they disabled online mode, so that offline account will be able to connect.
=> Can't you just think to use an offline account instead?

- ~~If you use LAN, would you think about account session duplication problem that would lead to different problems?~~

I’m pretty sure that then you would say this:
> I want to remain my skin on the second client

Again, Pojav doesn’t store stuff in `launcher_profiles.json`, since we are planned to remove offline account, we will not provide a way to Read-Write access the account data directly.

~~*What about getting another account then buy the game?*~~
