### ISSUE TITLE
I cannot find the mod folder <Short description>

### ISSUE THREAD

**Issue by camqu9** [PojavLauncherTeam/PojavLauncher#2333]
### Describe the bug

I looked around my phone and I didn't see the Minecraft folder in games

### Steps To Reproduce

```markdown
idk
```

### Expected Behavior

I expect to see it there

### Platform

```markdown
- Device model:Galaxy S20 5G 
- CPU architecture:64-Bit 
- Android version: 11
- PojavLauncher version: latest
```

### Anything else?

no

**Comment by GoneSubject** [comment]
you must follow this 
> you can find PojavLauncher files in sdcard/Android/data/net.kdt.pojavlaunch(.debug)/ files(on Android 10 or later) or sdcard/games/PojavLauncher/(on Android 9 or below)

**Comment by SprainedSpark89** [comment]
that probably means that there never a mod folder but maybe if you need a mod installer click the button under the select version if not i have to guess that you go to resourcepacks folder but idk anything else

**Comment by ghost** [comment]
Go to
Android/data/net.pojavlaunch.debug/files/.minecraft
(Enable show hidden files)

This is video tutorial
https://user-images.githubusercontent.com/70785472/144752980-fc317d8a-977f-4cd2-a0cd-43b2591b5d91.mp4

**Comment by GoneSubject** [comment]
._,

**Comment by Mathias-Boulay** [comment]
answer given, closing

**Comment by awesomebossdj7** [comment]
this should be reopened, there is no possible way to edit this folder now without rooting, new android versions will not allow you to edit or look inside of the "data" folder

even using third party apps, it will not allow you to select the folder because "to protect your privacy, use a different folder"

please move it back to sdcard/games or phone/games

**Comment by awesomebossdj7** [comment]
okay theres already a issue + i lied about rooting (more like i didnt know) and you gotta uninstall updates for your file explorer

**Comment by GaucovyAero** [comment]
> this should be reopened, there is no possible way to edit this folder now without rooting, new android versions will not allow you to edit or look inside of the "data" folder
> 
> even using third party apps, it will not allow you to select the folder because "to protect your privacy, use a different folder"
> 
> please move it back to sdcard/games or phone/games

on android 10+, you cant, if we did that, we wouldnt be able to exist on GPlay
moreover, the game being in /sdcard/games makes fabric crash because of permissions set in that folder

you either gotta uninstall updates, or if you cant, you gotta use com.marc.files from play store as a shortcut to your default files app (even the new update works fine), you can then access the pojav folder from the hamburger menu
