### ISSUE TITLE
Sodium operable?

### ISSUE THREAD

**Issue by aaaapai** [PojavLauncherTeam/PojavLauncher#2411]
### Describe the request.

Is there a patch?

**Comment by GoneSubject1** [comment]
yes sodium works but you mut use Virgl or Zink render, with gl4es will crash

**Comment by aaaapai** [comment]
Is this sure it won't lag? It's even more stuck！

**Comment by NotAHero04** [comment]
For the maximum performance, you may want to go with gl4es, with Sodium 0.1.x (Sodium 0.2.x maybe able with a shader patch)
If you want Sodium 0.2.x or later without further modification, use Zink/VirGL. It will slow down the game, though.
Even with a shader patch, Sodium 0.3.x and 0.4 will not run well with gl4es because the option to "Use compact vertex format" is enabled and cannot be disabled in the options.
You may be able to run it up to this point:
![2021-12-15_18 52 22](https://user-images.githubusercontent.com/84689840/146528711-774f2422-3701-48f4-a3d4-cf8c27cf1e1b.png)
but the game will crash as soon as it starts to render the world.
So, Sodium 0.3/0.4 for performance increase is NO GO, for now.

**Comment by khanhduytran0** [comment]
> Is this sure it won't lag? It's even more stuck！

If you use Zink just for get Sodium to work, think again. Zink is known to be a **slow** renderer. Use virglrenderer instead.
~~Hint: Get AMD Ryzen 9 5900X and RTX 3090 in order to fix lag.~~

Additionally, if you play 1.16.x or 1.17.x, use [PojavOptimize](https://github.com/Doregon/PojavOptimize).

**Comment by aaaapai** [comment]
> > Is this sure it won't lag? It's even more stuck！
> 
> If you use Zink just for get Sodium to work, think again. Zink is known to be a **slow** renderer. Use virglrenderer instead. ~Hint: Get AMD Ryzen 9 5900X and RTX 3090 in order to fix lag.~
> 
> Additionally, if you play 1.16.x or 1.17.x, use [PojavOptimize](https://github.com/Doregon/PojavOptimize).

I don't choose gl4es, it's meaningless for me to send this
I'd better wait for the notice!

**Comment by aaaapai** [comment]
> > Is this sure it won't lag? It's even more stuck！
> 
> If you use Zink just for get Sodium to work, think again. Zink is known to be a **slow** renderer. Use virglrenderer instead. ~Hint: Get AMD Ryzen 9 5900X and RTX 3090 in order to fix lag.~
> 
> Additionally, if you play 1.16.x or 1.17.x, use [PojavOptimize](https://github.com/Doregon/PojavOptimize).

I don't know how many times it takes to replace gl4es. It's not normal to choose another one because the number of frames is really low

**Comment by khanhduytran0** [comment]
> I don't know how many times it takes to replace gl4es. 

After all, gl4es is not RTX 3090 driver, so what do you expect? **it’s incomplete!**

**Comment by khanhduytran0** [comment]
Either playing with OptiFine; wait for Sodium devs to add an option to disable Compact Vertex Format; do one yourself; ~~insert RTX 3090 into your phone~~; or get a better device.

> <ins>I don't choose gl4es</ins>, it's meaningless for me to send this

then

> I don't know how many times it takes to replace gl4es. <ins>It's not normal to choose another one</ins> because the number of frames is really low

what do you mean then?
