### ISSUE TITLE
[F-Req] Touch and hold screen

### ISSUE THREAD

**Issue by andr0d1v** [PojavLauncherTeam/PojavLauncher#2424]
### Describe the request.

How do you like the idea to rewrite the mechanics of holding and touching the screen? So that they can hit mobs when pressed, hold to interact with mobs, and leave the same with blocks!

**Comment by khanhduytran0** [comment]
Minecraft Control settings exist for a reason. Mouse button keycode can be customized there.

**Comment by khanhduytran0** [comment]
If you mean to do the interaction exactly like Bedrock Edition, it’s impossible without modding. Why? Because it’s a PC game, which has never been designed for touch controls. It’s just a launcher, it doesn’t know which object that the player is pointing to, therefore it’s impossible to decide whether to send left or right mouse button without modding.
