### ISSUE TITLE
Why not build a plug-in center?

### ISSUE THREAD

**Issue by aaaapai** [PojavLauncherTeam/PojavLauncher#2458]
### Describe the request.

Put a plug-in center button in the launcher. After opening it, you can upload the plug-in about pojav launcher and review it. In this way, you can avoid many suggestions / problems.
![25](https://user-images.githubusercontent.com/89151134/147411010-c08c5d0b-73c7-45d2-932e-97f3b963ee99.png)

岂不美哉？（Baidu translation is not available in this Chinese）

### Anything else?

In addition, after installation, it will expand like a browser.
If you add a plug-in center, can you just fix APK bugs or modify APK?
Get another comment function
If there is no server, use GitHub

**Comment by khanhduytran0** [comment]
PojavLauncher supports 2 platforms: not just Android, but also iOS. Building a “plug-in center” requires implementing a compatibility API for both platforms.
But then, what’s the use of plug-in? A plug-in can’t be used to fix a renderer bug.
Implementing a plug-in requires the whole launcher rewrite in order to be modifiable in any parts.
It’s also unsafe as someone may embed a token logger into the plug-in.
