### ISSUE TITLE
Make .exe file run just like .jar files

### ISSUE THREAD

**Issue by JohnPrincePoggi31** [PojavLauncherTeam/PojavLauncher#2651]
### Is this request related to a bug?

You Should Add A Feature to Install .exe files to Pojav Launcher So More Clients Can be Added To Pojav
If Its Possible Or Not
Etc.
To Run Lunar client The file is .exe

### Describe the request.

A installer for .exe Files

**Comment by soup587** [comment]
this would probably be nigh impossible as .exe's are x64 windows based

**Comment by JohnPrincePoggi31** [comment]
Isnt there a way to put x64 windows to Android Or Iphone Or anything else
Just Curious

**Comment by CosineMath** [comment]
need x86/x64 emulator + wine
would be plenties of work but not very useful

**Comment by soup587** [comment]
^

I believe it's very slow as well

**Comment by khanhduytran0** [comment]
> Isnt there a way to put x64 windows to Android Or Iphone Or anything else

How do we emulate the entire x86_64 CPU in PojavLauncher just to... run Win32 installers instead of creating a separate app for running any Win32 executable? [Box64](https://github.com/ptitSeb/box64) and Wine are there, but the cost of storage is **too much**.

Actually, emulating Windows is not needed to run these installers, as most of these are built on top of Chromium, which turns out the entire installer/launcher is written in HTML+CSS+JavaScript. Therefore, it is possible to run it on a WebView, but a lot of file accessing APIs need to be implemented before it works.

Another problem is even if it’s installed somehow, will the client work?

**Comment by CosineMath** [comment]
better idea is to request authors of these clients provide .jar rather than .exe
