### ISSUE TITLE
1.16.5 optifine not working

### ISSUE THREAD

**Issue by saurabhris** [PojavLauncherTeam/PojavLauncher#2689]
### Describe the bug

When I play minecraft with optifine but exit the game at few moments

### The log file and images/videos

When I play minecraft with optifine but exit the game at few moments

### Steps To Reproduce

```markdown
1. Pls solve my problem When I play minecraft with optifine but exit the game at few moments
```

### Expected Behavior

When I play minecraft with optifine but exit the game at few moments

### Platform

```markdown
- Device model: iq z3

- CPU architecture: SD 768G
- Android version: 11
- PojavLauncher version: play store
```

**Comment by khanhduytran0** [comment]
`When I play minecraft with optifine but exit the game at few moments` is not a valid log file.
`1. Pls solve my problem When I play minecraft with optifine but exit the game at few moments` is not a valid step.
`When I play minecraft with optifine but exit the game at few moments` is not a valid expected behavior.

`play store` is an invalid PojavLauncher version.
