### ISSUE TITLE
[BUG] Cursed Fabric beta 1.7.3 doesn't work

### ISSUE THREAD

**Issue by NotAHero04** [PojavLauncherTeam/PojavLauncher#2742]
### Describe the bug

The game exited with code 1 on normal setting. The error could be fixed by setting some launch arguments, but the game still doesn't start.

### The log file and images/videos

Before setting the argument:
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8073031/latestlog.txt)

After setting the argument:
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8073039/latestlog.txt)

### Steps To Reproduce

```markdown
1. Download the Cursed Fabric installer and install it through the mod installer.
2. Choose and launch "cursed-fabric-loader-[commit_hash]-b1.7.3".
3. [The "Game/Application exited with code 1" popup will appear.] Back to the launcher, set the launch argument: -Dfabric.gameVersion="1.7.3"
4. Try launching the game again. [It will be stuck on a black screen indefinitely.]
```

### Expected Behavior

The game should be able to launch, or at least throw some useful errors.

### Platform

```markdown
- Device model: Vsmart Star 5
- CPU architecture: arm64
- Android version: 12 (GSI)
- PojavLauncher version: crocus-319-0a3385acd-v3_openjdk
```

### Anything else?

There could be a problem with game directory handling, because you must pass an argument to at least get rid of the first `java.lang.IllegalArgumentException`.

**Comment by 1493028** [comment]
What is cursed fabric??????)

**Comment by GaucovyAero** [comment]
> What is cursed fabric??????)

It's a mod loader. Normal Fabric is focused on versions of Minecraft ranging from 1.0 to 1.18.1 and later. On the other hand, Cursed Fabric is more focused on older versions than 1.0. It's a lot more "working" than Modloader, because Modloader needs things like damt.ModloaderTweaker to run in the Minecraft Launcher or pojav. Although one thing is true: more mods were made for Modloader b1.7.3 than Cursed Fabric b1.7.3.

**This is a screenshot of Cursed Fabric b1.7.3:**

![image](https://user-images.githubusercontent.com/85581164/154287306-3b1cf0a7-4282-4c2d-8f65-0c799923515f.png)

**Comment by GoneSubject** [comment]
> What is cursed fabric??????)

maybe [this](https://ftb.fandom.com/wiki/Cursed_Fabric) can answer

**Comment by SprainedSpark89** [comment]
pojavlauncher is not focused on supporting older versions i wish they were supporting new versions and older versions equally

**Comment by NotAHero04** [comment]
> pojavlauncher is not focused on supporting older versions i wish they were supporting new versions and older versions equally

Please be serious, and don't turn issues into your casual chat ever again.

**Comment by NotAHero04** [comment]
I and @Aerolome spent two months to find a fix for older Forge versions. Nothing is impossible.

**Comment by SprainedSpark89** [comment]
i wasn't trying to and is fabric even supported? normal fabric

**Comment by NotAHero04** [comment]
I tried snapping the normal Fabric Loader into the game and it does start. The mapping still fails, hence it will not work.

**Comment by GaucovyAero** [comment]
here's a patched babric 0.14.6 jar -> this goes into .minecraft/libraries, not directly, somewhere in there idk: https://www.mediafire.com/file/qzxiccvtctowzfq/fabric-loader-0.14.6-babric.1local.jar/file
- make sure to disable sha verification, otherwise it's gonna redownload the original jar

and here's artdev's pull request on mainline fabric, doesn't seem to be approved tho...
https://github.com/FabricMC/fabric-loader/pull/757/files

it's basically a simple issue in the applet, but yeah

**Comment by GaucovyAero** [comment]
the fix is now in fabric mainline and babric with the latest version of fabric loader starts up and works fine
https://babric.github.io/

**Comment by GaucovyAero** [comment]
heres the patched AppletMain.class file (has to be extracted): [AppletMain.zip](https://github.com/user-attachments/files/18271027/AppletMain.zip)

new install guide here (not babric! cause babric works):

https://github.com/user-attachments/assets/b8f20f60-9ae7-4141-9cea-363a1f2a30fd

timestamps:

0:00 installation as if it was on the stock Minecraft Launcher
1:33 fixing the "no valid game provider" error
4:06 fixing the duplicate asm library error by creating a custom version (i did an oopsie there, maybe watch the whole part first before doing it)
14:58 replacing the AppletMain.class so that the game can launch
21:27 the game finally launches!!

oh and the oopsie thing, dunno if this makes it any simpler but:
13:34 has to be done at 11:03 (you have to add a comma at the end of the line)
then you can easily continue at 13:34 and save a few minutes of hassle
