### ISSUE TITLE
External mouse [BUG] <Short description>

### ISSUE THREAD

**Issue by jiuhui0415** [PojavLauncherTeam/PojavLauncher#2761]
### Describe the bug

When Android uses an external mouse, there will be a mouse acceleration. Mouse acceleration is a way to determine the pointer position according to the speed, instead of the traditional one. The traditional is to determine the pointer position according to the moving area, so I hope to solve this problem through software. Turn off the mouse acceleration function, or suppress this function, of course, it is better to turn off the mouse acceleration. Hope to be resolved 

### The log file and images/videos

![Uploading 1645343765504..jpg…]()

### Steps To Reproduce

```markdown
When Android uses an external mouse, there will be a mouse acceleration. Mouse acceleration is a way to determine the pointer position according to the speed, instead of the traditional one. The traditional is to determine the pointer position according to the moving area, so I hope to solve this problem through software. Turn off the mouse acceleration function, or suppress this function, of course, it is better to turn off the mouse acceleration. Hope to be resolved
```

### Expected Behavior

When Android uses an external mouse, there will be a mouse acceleration. Mouse acceleration is a way to determine the pointer position according to the speed, instead of the traditional one. The traditional is to determine the pointer position according to the moving area, so I hope to solve this problem through software. Turn off the mouse acceleration function, or suppress this function, of course, it is better to turn off the mouse acceleration. Hope to be resolved 

### Platform

```markdown
redmi note 7 pro/128g
aarch64
redmi note 7 pro
aarch64:Latest version pojavlaucher
```

### Anything else?

When Android uses an external mouse, there will be a mouse acceleration. Mouse acceleration is a way to determine the pointer position according to the speed, instead of the traditional one. The traditional is to determine the pointer position according to the moving area, so I hope to solve this problem through software. Turn off the mouse acceleration function, or suppress this function, of course, it is better to turn off the mouse acceleration. Hope to be resolved

**Comment by GaucovyAero** [comment]
Well, it's not a "bug", and it's not even caused by PojavLauncher itself. It's caused by Android and there is no setting to turn it off.  I am personally very annoyed by this when using an external mouse in PojavLauncher, but you just have to deal with it. There is one [forum post](https://www.reddit.com/r/SamsungDex/comments/of0hby/turn_off_pointer_acceleration/) on the Samsung DeX subreddit about mouse accel, but that's about it. 

**Final: You can't disable mouse acceleration in Android.**

*If you get your mouse working without mouse acceleration on Android, please let me know, thanks :D
