### ISSUE TITLE
[F-Req] WHEN WILL VGPU 4.0 Opengl 4.0 come?

### ISSUE THREAD

**Issue by MARnelPH12** [PojavLauncherTeam/PojavLauncher#2909]
### Is this request related to a bug?

No.

### Describe the request.

Im just thinking when would virgl renderer updated like 3.9 or something else.

### Anything else?

NOTHIN.

**Comment by khanhduytran0** [comment]
You might not know that most shaders don’t require OpenGL 4. Even SEUS PTGI E12, only GLSL 3.30 (compatibility profile) is used.
But the problem is: is your device's GPU powerful enough to handle it? Also, translated shader may contain a few incompatibility stuff.
OpenGL 3.9 didn’t exist.
Updating renderers are actually not our job, as we mostly work on the launcher part.

**Comment by mchnjt** [comment]
> ### Is this request related to a bug?
> No.
> 
> ### Describe the request.
> Im just thinking when would virgl renderer updated like 3.9 or something else.
> 
> ### Anything else?
> NOTHIN.

port opengl 4.6 to androd then

**Comment by GaucovyAero** [comment]
> > ### Is this request related to a bug?
> > No.
> > ### Describe the request.
> > Im just thinking when would virgl renderer updated like 3.9 or something else.
> > ### Anything else?
> > NOTHIN.
> 
> port opengl 4.6 to androd then

**zink** moment
