### ISSUE TITLE
Make it compatible for batmod and other clients

### ISSUE THREAD

**Issue by padamchauhan** [PojavLauncherTeam/PojavLauncher#2941]

**Comment by GaucovyAero** [comment]
Some do work, some don't. That's just how it goes. Most of them don't work, because they require the DiscordRPC library (which shows what game you are playing on discord), but of course, it doesn't work on Android, so you are left with a crash and a non-working client. Ones that work:

OCMC (1.7.10)
Sol Client (1.8.9)
cmpack (1.8.8)
