### ISSUE TITLE
NEI mod does not work 1.7.10

### ISSUE THREAD

**Issue by CaduEdu13** [PojavLauncherTeam/PojavLauncher#2963]
### Describe the bug

One of, if not the most important of the mods is not working. The "Notenoughitens" or NEI, for version 1.7.10. Even it alone without any other mod, does not start. I've tried everything. I even downloaded a modified version.

### The log file and images/videos

..

### Steps To Reproduce

```markdown
download the mod. enter version 1.7.10 with mod
```

### Expected Behavior

Hope you fix this so I can get back to working on my modpack

### Platform

```markdown
- Device model: MotoG6 Play/32G
- CPU architecture: 
- Android version: 9
- PojavLauncher version: crocus-v3_openjdk
```

### Anything else?

No

**Comment by GaucovyAero** [comment]
You didn't send logs, but I presume it's because of a broken download for CodeChickenLib. I can't send it here, so you will need to find it yourself.

Just put the file I sent into .minecraft/mods/1.7.10/ 

Please note that just putting it in mods doesn't work! You need the 1.7.10 folder and then put it into there (the 1.7.10 folder).
