### ISSUE TITLE
[BUG] Shift bug on inventory (repost)

### ISSUE THREAD

**Issue by ZaphHG** [PojavLauncherTeam/PojavLauncher#2966]
### Describe the bug

the bug consists of the item being pulled with shift without me even pressing shift, or I click with shift + left mouse button and not creating all the items I want 
the shift is pressed by itself, by the game itself, at no time during the first crafting did I click on shift
this is very discouraging and I wish it would be fixed, I love playing in pojavlauncher but this is discouraging me
this is not a bug of the touchscreen ON/OFF (located in Controls).

this is not a problem with my keyboard, a friend of mine also has this same problem with shift

this bug makes it impossible to play HG or bed wars

### The log file and images/videos

https://youtu.be/KSq9YS1_g74

### Steps To Reproduce

```markdown
1: just log into the game, into a solo world or an online game and try to recreate the steps in the video, my minecraft version is 1.8.8 (CM PACK)
```

### Expected Behavior

I would expect the shift to work normally when I press it, and not on its own, this is becoming a problem.

### Platform

```markdown
- Device model: Tab S6 Lite / 64GB
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: TextView -> Renderer Android CI #3673 / Actions v3_openjdk
```

**Comment by DovydasTEDS** [comment]
I am also currently running into the same issue.

**Comment by swarties** [comment]
Same issue for me

**Comment by swarties** [comment]
It's impossible to remap keys in settings

**Comment by swarties** [comment]
@Mathias-Boulay has any advancement in this been made, since I really want to play bedwars without this bug, it is really frustrating.

**Comment by Leinator** [comment]
To add some clarification because OP's explanation is a little convoluted:

When you press shift + click while using keyboard mouse while in the inventory UI, the game behaves as if shift is being held down after you stop pressing shift. If you exit the UI, you will be crouched until you press shift again. Using shift while not in the inventory UI behaves normally. This is not a settings issue, shift is not set to toggle and its not a sticky keys issue with android. Multiple users have reported it on discord and reddit.

**Comment by Mathias-Boulay** [comment]
Should be mitigated now
