### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by khanhduytran0** [PojavLauncherTeam/PojavLauncher#3]
Note that this list is for v2. Known issues list is currently on README.md.

### PojavLauncher is not yet stable. There are some known issues:
- Can't see skin or join premium servers even with login to Mojang account.
- Missing Java API cause client crash randomly.
- Launcher UI didn't fit the big screen.
- Pointer capture API not working.

### Solved issues:
- Minecraft 1.9~1.11 and above got double letters while entering text.
- Lost crash log in Crash Report tab.
- Touch event triggered as click event.
- In-game, arrows key recognize as NONE key.
- No audio, OpenAL error.

**Comment by artdeell** [comment]
> PojavLauncher is not yet stable. There are some known issues:
> 
>     * Not able to authenticate to Mojang Account.
> 
>     * Missing Java API cause client crash randomly.
> 
>     * Launcher UI didn't fit the big screen.
> 
>     * Lost crash log in Crash Report tab.
It can authetificate Mojang accounts. I tested

**Comment by khanhduytran0** [comment]
But you can't see your skin or join premium servers.

**Comment by abdo-A028** [comment]
Hey Tran Khanh, I can't download updates like 20w13a.
Can I see what can you do?

**Comment by khanhduytran0** [comment]
You can't even run because launcher didn't support 1.13 or higher. 20w13a is a part of 1.16

**Comment by abdo-A028** [comment]
Even this updateWhen will you fix this?Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: khanhduytran0 <notifications@github.com> Date: 26/03/2020  00:07  (GMT+02:00) To: khanhduytran0/PojavLauncher <PojavLauncher@noreply.github.com> Cc: abdo-A028 <abdulrahman.adel2006@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [khanhduytran0/PojavLauncher] Known Issues (#3) 
You can't even run because launcher didn't support 1.13 or higher. 20w13a is a part of 1.16

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/khanhduytran0/PojavLauncher/issues/3#issuecomment-604112459",
"url": "https://github.com/khanhduytran0/PojavLauncher/issues/3#issuecomment-604112459",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by khanhduytran0** [comment]
Not just fix, to make 1.13 and above working, LWJGL3 and GLFW must be ported to Android, there is only LWJGL3 with GLES API and no GLFW.

**Comment by artdeell** [comment]
@khanhduytran0 take look at this
https://github.com/xCuri0/glfw-android-example

**Comment by khanhduytran0** [comment]
It's native code only without JNI wrapper while my knowledge about C/C++ are very low.

**Comment by khanhduytran0** [comment]
Is it already have JNI wrapper in liblwjgl3?

**Comment by khanhduytran0** [comment]
Optifine is going to be worked:
```
---- 26-03-2020 10:04:31 ----
I/LaunchWrapper(11286): Loading tweak class name optifine.OptiFineTweaker
I/LaunchWrapper(11286): Using primary tweak class name optifine.OptiFineTweaker
I/LaunchWrapper(11286): Calling tweak class optifine.OptiFineTweaker
I/System.out(11286): OptiFineTweaker: acceptOptions
I/System.out(11286): OptiFineTweaker: injectIntoClassLoader
I/System.out(11286): OptiFine ClassTransformer
W/System.err(11286): java.lang.NullPointerException: Attempt to invoke virtual method 'java.security.CodeSource java.security.ProtectionDomain.getCodeSource()' on a null object reference
W/System.err(11286): 	at optifine.OptiFineClassTransformer.<init>(OptiFineClassTransformer.java:40)
W/System.err(11286): 	at java.lang.reflect.Constructor.newInstance(Native Method)
W/System.err(11286): 	at java.lang.Class.newInstance(Class.java:1572)
W/System.err(11286): 	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:140)
W/System.err(11286): 	at optifine.OptiFineTweaker.injectIntoClassLoader(OptiFineTweaker.java:40)
W/System.err(11286): 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:114)
W/System.err(11286): 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
W/System.err(11286): 	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:685)
W/System.err(11286): 	at net.kdt.pojavlaunch.MainActivity.access$1000072(MainActivity.java)
W/System.err(11286): 	at net.kdt.pojavlaunch.MainActivity$100000012$100000011.run(MainActivity.java:489)
W/System.err(11286): 	at java.lang.Thread.run(Thread.java:818)
I/System.out(11286): *** Can not find the OptiFine JAR in the classpath ***
I/System.out(11286): *** OptiFine will not be loaded! ***
I/System.out(11286): OptiFineTweaker: getLaunchArguments
I/System.out(11286): OptiFineTweaker: getLaunchTarget
I/LaunchWrapper(11286): Launching wrapped minecraft {net.minecraft.client.main.Main}
---- 26-03-2020 10:04:48 ----
```

I decompiled some codes in Optifine instlaller, some patchs will be applied to the installer to make it work.

**Comment by abdo-A028** [comment]
Ok, but which android phoneSent from my Samsung Galaxy smartphone.
-------- Original message --------From: khanhduytran0 <notifications@github.com> Date: 26/03/2020  01:20  (GMT+02:00) To: khanhduytran0/PojavLauncher <PojavLauncher@noreply.github.com> Cc: abdo-A028 <abdulrahman.adel2006@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [khanhduytran0/PojavLauncher] Known Issues (#3) 
Not just fix, to make 1.13 and above working, LWJGL3 and GLFW must be ported to Android, there is only LWJGL3 with GLES API and no GLFW.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/khanhduytran0/PojavLauncher/issues/3#issuecomment-604139885",
"url": "https://github.com/khanhduytran0/PojavLauncher/issues/3#issuecomment-604139885",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by khanhduytran0** [comment]
My device. Also might be any devices in preview6

**Comment by abdo-A028** [comment]
That's niceSent from my Samsung Galaxy smartphone.
-------- Original message --------From: khanhduytran0 <notifications@github.com> Date: 26/03/2020  09:06  (GMT+02:00) To: khanhduytran0/PojavLauncher <PojavLauncher@noreply.github.com> Cc: abdo-A028 <abdulrahman.adel2006@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [khanhduytran0/PojavLauncher] Known Issues (#3) 
Optifine is going to be worked:
---- 26-03-2020 10:04:31 ----
I/LaunchWrapper(11286): Loading tweak class name optifine.OptiFineTweaker
I/LaunchWrapper(11286): Using primary tweak class name optifine.OptiFineTweaker
I/LaunchWrapper(11286): Calling tweak class optifine.OptiFineTweaker
I/System.out(11286): OptiFineTweaker: acceptOptions
I/System.out(11286): OptiFineTweaker: injectIntoClassLoader
I/System.out(11286): OptiFine ClassTransformer
W/System.err(11286): java.lang.NullPointerException: Attempt to invoke virtual method 'java.security.CodeSource java.security.ProtectionDomain.getCodeSource()' on a null object reference
W/System.err(11286): 	at optifine.OptiFineClassTransformer.<init>(OptiFineClassTransformer.java:40)
W/System.err(11286): 	at java.lang.reflect.Constructor.newInstance(Native Method)
W/System.err(11286): 	at java.lang.Class.newInstance(Class.java:1572)
W/System.err(11286): 	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:140)
W/System.err(11286): 	at optifine.OptiFineTweaker.injectIntoClassLoader(OptiFineTweaker.java:40)
W/System.err(11286): 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:114)
W/System.err(11286): 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
W/System.err(11286): 	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:685)
W/System.err(11286): 	at net.kdt.pojavlaunch.MainActivity.access$1000072(MainActivity.java)
W/System.err(11286): 	at net.kdt.pojavlaunch.MainActivity$100000012$100000011.run(MainActivity.java:489)
W/System.err(11286): 	at java.lang.Thread.run(Thread.java:818)
I/System.out(11286): *** Can not find the OptiFine JAR in the classpath ***
I/System.out(11286): *** OptiFine will not be loaded! ***
I/System.out(11286): OptiFineTweaker: getLaunchArguments
I/System.out(11286): OptiFineTweaker: getLaunchTarget
I/LaunchWrapper(11286): Launching wrapped minecraft {net.minecraft.client.main.Main}
---- 26-03-2020 10:04:48 ----

I decompiled some codes in Optifine instlaller, some patchs will be applied to the installer to make it work.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/khanhduytran0/PojavLauncher/issues/3#issuecomment-604265861",
"url": "https://github.com/khanhduytran0/PojavLauncher/issues/3#issuecomment-604265861",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by abdo-A028** [comment]
Hey, we can download Minecraft java 1.12.2, but it doesn't workSent from my Samsung Galaxy smartphone.
-------- Original message --------From: khanhduytran0 <notifications@github.com> Date: 26/03/2020  14:40  (GMT+02:00) To: khanhduytran0/PojavLauncher <PojavLauncher@noreply.github.com> Cc: abdo-A028 <abdulrahman.adel2006@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [khanhduytran0/PojavLauncher] Known Issues (#3) 
My device. Also might be any devices in preview6

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/khanhduytran0/PojavLauncher/issues/3#issuecomment-604408149",
"url": "https://github.com/khanhduytran0/PojavLauncher/issues/3#issuecomment-604408149",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by khanhduytran0** [comment]
https://github.com/khanhduytran0/PojavLauncher/issues/7#issuecomment-603217038

**Comment by khanhduytran0** [comment]
@artdeell OptiFine is a bit more worked. https://youtu.be/k_d_AxglnZU
After a black screen it crash. [tombstone_09.txt](https://github.com/khanhduytran0/PojavLauncher/files/4390703/tombstone_09.txt)

EDIT: `inheritsFrom` tag has been implemented.

**Comment by abdo-A028** [comment]
What is 1.7.1.0 optifineSent from my Samsung Galaxy smartphone.
-------- Original message --------From: khanhduytran0 <notifications@github.com> Date: 27/03/2020  02:10  (GMT+02:00) To: khanhduytran0/PojavLauncher <PojavLauncher@noreply.github.com> Cc: abdo-A028 <abdulrahman.adel2006@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [khanhduytran0/PojavLauncher] Known Issues (#3) 
@artdeell OptiFine is a bit more worked. https://youtu.be/k_d_AxglnZU
After a black screen it crash. tombstone_09.txt

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/khanhduytran0/PojavLauncher/issues/3#issuecomment-604749371",
"url": "https://github.com/khanhduytran0/PojavLauncher/issues/3#issuecomment-604749371",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by khanhduytran0** [comment]
OptiFine 1.7.10 HD U E7

**Comment by abdo-A028** [comment]
I tested this and it is loading for a yearJoking not a yearSent from my Samsung Galaxy smartphone.
-------- Original message --------From: khanhduytran0 <notifications@github.com> Date: 27/03/2020  11:31  (GMT+02:00) To: khanhduytran0/PojavLauncher <PojavLauncher@noreply.github.com> Cc: abdo-A028 <abdulrahman.adel2006@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [khanhduytran0/PojavLauncher] Known Issues (#3) 
OptiFine 1.7.10 HD U E7

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/khanhduytran0/PojavLauncher/issues/3#issuecomment-604902857",
"url": "https://github.com/khanhduytran0/PojavLauncher/issues/3#issuecomment-604902857",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by khanhduytran0** [comment]
(known issues may need to move to other)

**Comment by HerobrineH9788** [comment]
In Android 8.1.0, you can only play from 1.5 to 17w06a versions of minecraft! 1.12 has got Errors on his way of logging in, and 1.13+ have got broken Files that don't  match! Could you fix this Issue?

**Comment by khanhduytran0** [comment]
> In Android 8.1.0, you can only play from 1.5 to 17w06a versions of minecraft! 1.12 has got Errors on his way of logging in, and 1.13+ have got broken Files that don't  match! Could you fix this Issue? 

Maybe not at all with v2, and maybe in v3 (not done yet)...

**Comment by HerobrineH9788** [comment]
Can't open versions of Minecraft [1.12-17w13a to 1.13-17w50] Error shown while Opening the game!

Can't Convert the 1.13+ versions of Minecraft. 

Game running always at 0 - 29 fps.

Thesee issues happent on Androind 8.1.0

**Comment by HerobrineH9788** [comment]
I cant get a Data pack to work on my world.

+Can't put a resource pack on the Pack [Settings]¡

**Comment by khanhduytran0** [comment]
So when you press a pack it doesn't change?

**Comment by HerobrineH9788** [comment]
Yes, When I try to activate Datapacks, nothing happens! It must be an issue
from Minecraft, not from The PojavLauncher!

-How do I put Resource Packs on to the pack settings?

Më Mër, 29 Kor 2020, 05:06 Tran Khanh Duy <notifications@github.com> shkroi:

**Comment by khanhduytran0** [comment]
You may check
- If Minecraft is not responding (button not highlight) because Minecraft may load datapack for a while.
- Check for log output while datapack is loading.
- Wait for a while.

**Comment by khanhduytran0** [comment]
Or continue dm me on discord?

**Comment by HerobrineH9788** [comment]
Ok, Thanks for helping!

Më Mër, 29 Kor 2020, 07:48 Tran Khanh Duy <notifications@github.com> shkroi:

**Comment by HerobrineH9788** [comment]
Ok

Më Mër, 29 Kor 2020, 07:49 Tran Khanh Duy <notifications@github.com> shkroi:

**Comment by BryleHelll** [comment]
> That's niceSent from my Samsung Galaxy smartphone. -------- Original message --------From: khanhduytran0 <notifications@github.com> Date: 26/03/2020 09:06 (GMT+02:00) To: khanhduytran0/PojavLauncher <PojavLauncher@noreply.github.com> Cc: abdo-A028 <abdulrahman.adel2006@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [khanhduytran0/PojavLauncher] Known Issues (#3) Optifine is going to be worked: ---- 26-03-2020 10:04:31 ---- I/LaunchWrapper(11286): Loading tweak class name optifine.OptiFineTweaker I/LaunchWrapper(11286): Using primary tweak class name optifine.OptiFineTweaker I/LaunchWrapper(11286): Calling tweak class optifine.OptiFineTweaker I/System.out(11286): OptiFineTweaker: acceptOptions I/System.out(11286): OptiFineTweaker: injectIntoClassLoader I/System.out(11286): OptiFine ClassTransformer W/System.err(11286): java.lang.NullPointerException: Attempt to invoke virtual method 'java.security.CodeSource java.security.ProtectionDomain.getCodeSource()' on a null object reference W/System.err(11286): at optifine.OptiFineClassTransformer.<init>(OptiFineClassTransformer.java:40) W/System.err(11286): at java.lang.reflect.Constructor.newInstance(Native Method) W/System.err(11286): at java.lang.Class.newInstance(Class.java:1572) W/System.err(11286): at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:140) W/System.err(11286): at optifine.OptiFineTweaker.injectIntoClassLoader(OptiFineTweaker.java:40) W/System.err(11286): at net.minecraft.launchwrapper.Launch.launch(Launch.java:114) W/System.err(11286): at net.minecraft.launchwrapper.Launch.main(Launch.java:28) W/System.err(11286): at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:685) W/System.err(11286): at net.kdt.pojavlaunch.MainActivity.access$1000072(MainActivity.java) W/System.err(11286): at net.kdt.pojavlaunch.MainActivity$100000012$100000011.run(MainActivity.java:489) W/System.err(11286): at java.lang.Thread.run(Thread.java:818) I/System.out(11286): *** Can not find the OptiFine JAR in the classpath *** I/System.out(11286): *** OptiFine will not be loaded! *** I/System.out(11286): OptiFineTweaker: getLaunchArguments I/System.out(11286): OptiFineTweaker: getLaunchTarget I/LaunchWrapper(11286): Launching wrapped minecraft {net.minecraft.client.main.Main} ---- 26-03-2020 10:04:48 ---- I decompiled some codes in Optifine instlaller, some patchs will be applied to the installer to make it work. —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe. [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/khanhduytran0/PojavLauncher/issues/3#issuecomment-604265861", "url": "https://github.com/khanhduytran0/PojavLauncher/issues/3#issuecomment-604265861", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

Your github is kind of wierd

**Comment by myxiaomo** [comment]
Running Nei and other playable modules will crash

**Comment by AmadeusDoesStuff** [comment]
Select account issue on tablets
