### ISSUE TITLE
[F-Req] <Short description>

### ISSUE THREAD

**Issue by Meddl420** [PojavLauncherTeam/PojavLauncher#3169]
### Is this request related to a bug?

Please enable me to i change my skin

**Comment by offbeat-stuff** [comment]
what do you mean, if you want to change skin you need to change it from your account setting or use a mod to change it or the cosmetica thingy.

**Comment by kuzy21** [comment]
If you want to change your skin then buy minecraft simple, don't be a pirate

**Comment by kuzy21** [comment]
Close this issue

**Comment by khanhduytran0** [comment]
You can go to [your profile](https://minecraft.net/en-us/profile/skin) to change.
If you ask why we don’t make a custom skin changer like TLauncher:
- We have disabled the download functionally for the `offline account`, became `local account`, and stopped supporting pirates for legal reasons.
- By having `steve.png` changer, it’s just like selfie (only you can see it) so you will ask why not create a skin server: Due to the reason above ^
