### ISSUE TITLE
[F-Req] <Getting a full-fledged Linux instead of an installer.jar>

### ISSUE THREAD

**Issue by Waxbyz** [PojavLauncherTeam/PojavLauncher#3215]
### Is this request related to a bug?

You should add a full Linux instead of an installer.jar

### Describe the request.

You should add a full Linux instead of an installer.jar

### Anything else?

You should add a full Linux instead of an installer.jar

**Comment by khanhduytran0** [comment]
This is already what [UserLAnd](https://play.google.com/store/apps/details?id=tech.ula) (no root) and [Linux Deploy](https://play.google.com/store/apps/details?id=ru.meefik.linuxdeploy) (root required) do, Termux also has [proot-distro](https://github.com/termux/proot-distro). These can be installed separately.

So what’s the problem when put to PojavLauncher?
- Putting a Linux distribution just to run installers like Lunar Client is pointless, since they only support x86 (Intel, AMD CPU) and not ARM (Snapdragon, Mediatek, Kirin, etc..). [Box64](https://github.com/ptitSeb/box64)? 
- App size: *stonks*. You may find that [Alpine Linux](https://alpinelinux.org/about), the lightest distribution, takes 130 MB. But that’s just the base, X11 libraries take much more.
- Getting hardware-accelerated X11 server is the whole pain. Without hardware acceleration, it would be way slower. We spent months trying to get [gl-streaming](https://github.com/khanhduytran0/android-gl-streaming) as a way for hardware acceleration, but it has never been finished.
- This is not our goal. It’s too complicated to achieve it. v3.0-v3.1 actually embedded a small Debian system in it. However, a lot of problems came (see #142 for full discussion).
