### ISSUE TITLE
[F-Req] Android 12 is not supported?

### ISSUE THREAD

**Issue by UzakaZinnMC758** [PojavLauncherTeam/PojavLauncher#3217]
### Is this request related to a bug?

It is related to the "Exit code 1" error. But that happened when I played 1.18 before. But now can't get into 1.16!

### Describe the request.

I wish Pojavlauncher Team support Android 12 quickly. My machine configuration:
Vivo Y21s
Mediatek Helio G80
Android 12 (Release)
aarch64

### Anything else?

Thank Pojavlauncher

**Comment by GaucovyAero** [comment]
I am indeed using LineageOS 19 - Android 12 totally fine, and even 1.18.2 works fine. Devs are currently working really hard to get Forge working on 1.17 and 1.18. Thing is, for 1.16 at least, you have to send logs so that we can actually figure out what's the issue. For 1.18 support, just update pojav to the latest [Actions](https://github.com/PojavLauncherTeam/PojavLauncher/actions) build. Download app-debug.zip, then extract the archive and install app-debug.apk, and you're done.

**Comment by WesleyVanNeck** [comment]
it even runs on android 12.1
