### ISSUE TITLE
Idk of it's just for m but anytime I try and run any version it crashes any idea how to fix it

### ISSUE THREAD

**Issue by Daveied** [PojavLauncherTeam/PojavLauncher#3290]
### Describe the bug

It always says game exited with code 1 see latestlog.txt for more detail 

### The log file and images/videos

https://photos.app.goo.gl/P9fxc2pNBdTpUqE89

### Steps To Reproduce

```markdown
1)start pojav
2)select my account
3)run any version (impact,forge,wurst)
4)wait for I to load
5)crash
```

### Expected Behavior

Happens everytime I try to play

### Platform

```markdown
- Device model: 
- CPU architecture: no idea how to check
- Android version: 9
- PojavLauncher version: latest
```

**Comment by GaucovyAero** [comment]
Knowing the CPU architecture is essential for us to know, what the underlying issue is, but I presume it's the unpacking issue with ARM32. The dev team is currently working hard to fix it. For the time being, download [this](https://github.com/PojavLauncherTeam/PojavLauncher/suites/6163586812/artifacts/215927153) old build.

**Comment by Mathias-Boulay** [comment]
fixed I guess
