### ISSUE TITLE
[BUG] Screen Bug

### ISSUE THREAD

**Issue by A-New-Light** [PojavLauncherTeam/PojavLauncher#3334]
### Describe the bug

When ever i open my game it has a weird screen glitch where it moves up to the top of the screen while loading, is there any fix for this?

### The log file and images/videos

![Screenshot 2022-06-05 9 56 18 AM](https://user-images.githubusercontent.com/104699298/172051669-7992927e-0810-4f2a-b5e2-2782cae1c757.png)

### Steps To Reproduce

```markdown
1. start povjav
2. run cmpack 1.8.8
3. wait for screen glitch
```

### Expected Behavior

i expected the game to work fine but it doesnt

### Platform

```markdown
- Device model: Hp Chromebook 11 G8 
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: idk the newest one on the play store
```

**Comment by Mathias-Boulay** [comment]
unofficial client I see

**Comment by Mathias-Boulay** [comment]
Can the issue be reproduced with a vanilla version ?

**Comment by GaucovyAero** [comment]
> Can the issue be reproduced with a vanilla version ?

The issue is just the cmpack loading screen, it probably just doesn't "fullscreen" or something when loading. It runs just fine when Minecraft starts. It isn't really a gamebreaking issue or anything, at least from my perspective. Also, I presume it can't be reproduced on vanilla, because I also use cmpack and have this loading menu issue. But as I said, it isn't really an issue for me.
