### ISSUE TITLE
[F-Req] Mod that isnt working support

### ISSUE THREAD

**Issue by Jamespoxdxdxd** [PojavLauncherTeam/PojavLauncher#3380]
### Is this request related to a bug?

 what is your guys planned for mod that isnt working is it just going to be forever not gonna work? For example Sodium 
and not only the mod and the virgl crash when you use Fast Render ON aswell for 1.17-1.19+ When you turn on Render Regions it crash

### Describe the request.

I Hope someday in future this will be fix

### Anything else?

.

**Comment by GaucovyAero** [comment]
> ### Is this request related to a bug?
> what is your guys planned for mod that isnt working is it just going to be forever not gonna work? For example Sodium and not only the mod and the virgl crash when you use Fast Render ON aswell for 1.17-1.19+ When you turn on Render Regions it crash
> 
> ### Describe the request.
> I Hope someday in future this will be fix
> 
> ### Anything else?
> .

Okay, so as to the bugs, we cannot fix them.
1. Sodium needs extensions that aren't supported by gl4es and Sodium also crashes on old GPUs (see Intel GMA X3100). Sodium works with VirGL tho (with terrible VirGL performance of course, so Sodium + VirGL is dramatically slower than vanilla + gl4es)
2. VirGL doesn't crash when you select Fast Render, it's just that the image is outside of your screen. If you were to download versions of Pojav with VirGL from 6 months ago and you would "un-fullscreen" Minecraft, you will actually see what's going on. This cannot be fixed, because VirGL isn't our project and it has to use "Slow Render" or however you want to call it for it to work.
3. The Render Regions crash is caused by a graphical function that Minecraft calls that is not present in Pojav (the same as the Sodium problem), so again, we can't fix this issue.

**Comment by yum13241** [comment]
Sodium works with VirGL, but the game is rendered upside down for me.

**Comment by Jamespoxdxdxd** [comment]
> > ### Is this request related to a bug?
> > what is your guys planned for mod that isnt working is it just going to be forever not gonna work? For example Sodium and not only the mod and the virgl crash when you use Fast Render ON aswell for 1.17-1.19+ When you turn on Render Regions it crash
> > ### Describe the request.
> > I Hope someday in future this will be fix
> > ### Anything else?
> > .
> 
> Okay, so as to the bugs, we cannot fix them.
> 
> 1. Sodium needs extensions that aren't supported by gl4es and Sodium also crashes on old GPUs (see Intel GMA X3100). Sodium works with VirGL tho (with terrible VirGL performance of course, so Sodium + VirGL is dramatically slower than vanilla + gl4es)
> 2. VirGL doesn't crash when you select Fast Render, it's just that the image is outside of your screen. If you were to download versions of Pojav with VirGL from 6 months ago and you would "un-fullscreen" Minecraft, you will actually see what's going on. This cannot be fixed, because VirGL isn't our project and it has to use "Slow Render" or however you want to call it for it to work.
> 3. The Render Regions crash is caused by a graphical function that Minecraft calls that is not present in Pojav (the same as the Sodium problem), so again, we can't fix this issue.

oh ok:(

**Comment by Mathias-Boulay** [comment]
#1948
