### ISSUE TITLE
2 bugs in one render. HOLY GL4ES.

### ISSUE THREAD

**Issue by selut06** [PojavLauncherTeam/PojavLauncher#3484]
### Describe the bug

> as you can see on screen shot, half of the rights screen is lower resolution than the left (zoom it for little detail).

> second one, idk how to tell but  you can see on the vid. mouse disappear when turn off gui.

### The log file and images/videos

![Picsart_22-08-11_19-13-13-638](https://user-images.githubusercontent.com/82783126/184121191-1caef908-8d29-4734-b2cd-cde50575042d.png)

https://user-images.githubusercontent.com/82783126/184121444-07c00128-fdb7-4364-86a6-e1e06a95f6f1.mp4

### Steps To Reproduce

```markdown
-open pojav
-use holy gles
-run
```

### Expected Behavior

...

### Platform

```markdown
- Device model: LG G7
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: lastest release
```

### Anything else?

yeah, fix it. lol.

> (This only happens to gl4es, Virgl is totally fine)

**Comment by GaucovyAero** [comment]
I mean, your screenshot and video didn't upload, so I have absolutely no idea what's wrong.

**Comment by selut06** [comment]
> I mean, your screenshot and video didn't upload, so I have absolutely no idea what's wrong.

fixed, now u can check

**Comment by Mathias-Boulay** [comment]
"latest release ?"

**Comment by selut06** [comment]
> "latest release ?"

all versions that has " holy gl4es "

**Comment by GaucovyAero** [comment]
1. - This is normal, you get it even on PCs if you have a resolution different than 720p or 1080p. It may work on some resolution different than those, but 720p and 1080p definitely always do work correctly if Normal GUI Scale is being used.
2. - The mouse dissapearing bug is caused by Alternate surface rendering being enabled in the Video and renderer tab in PojavLauncher. Alternate surface rendering makes the game run faster at lower resolutions, but slower at higher resolutions. And as a side effect, it produces this virtual mouse issue by simultaneously giving better performance in some cases.
