### ISSUE TITLE
[BUG] Forge does not install (1.16.5)

### ISSUE THREAD

**Issue by Tetralink** [PojavLauncherTeam/PojavLauncher#3622]
### Describe the bug

I can't install Forge on PojavLauncher.
When I install it, it brings me back to the launcher.
I searched the internet for solutions: on youtube and on the github.
I tried several versions of java but nothing worked. Either there is an error code, or it returns to the launcher.
Can you help me ?

https://user-images.githubusercontent.com/116966890/198875733-4d2939d4-4106-4673-a4d1-06119eff02ee.mp4

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9895677/latestlog.txt)

### Steps To Reproduce

```markdown
1. start PojavLauncher
2. go to option
3. choose the first option
4. install forge
5. the bug occurs
```

### Expected Behavior

I was waiting for forge to install but... its bug

### Platform

```markdown
- Device model: Galaxy A02s 3/32G
- CPU architecture: aarch64
- Android version: 12 
- PojavLauncher version: 3.3.1.1
```

### Anything else?

Sorry for the poor quality video, my badly written message and my bad traduction.
I also tried removing quotes in latestlog.txt

**Comment by endervad** [comment]
Looks like you have older version since for me the UI looks a bit different - I grabbed this one: https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/3356958656
There's a separate "Install JAR" button now. I successfully installed Forge using this, but keep in mind that you have to use "Force Close" button if the installer screen doesn't close itself after success. Otherwise for me it didn't create a separate instance.

**Comment by Tetralink** [comment]
Thanks for the release. Indeed, I did not have this version but now the application quits with error code 1 when I download Forge with .jar.

**Comment by Tetralink** [comment]
I finally managed to install it thank you very much for your help
