### ISSUE TITLE
[F-Req]Give Shader Support Virgl For All GPU>

### ISSUE THREAD

**Issue by Jazlenkate** [PojavLauncherTeam/PojavLauncher#3857]
### Is this request related to a bug?

You should give shader support to all GPU on virgl Renderer 

### Describe the request.

Shader Support For Virgl All GPU because it's only supported is MALI GPU so Support the Other GPU Like On PVR, Andreno Plss

**Comment by mchnjt** [comment]
We infamously know that Shader Support is **very** unstable. Even the most common PC shaders won't even run on PojavLauncher

VirGL; at this very moment, isn't even stable for the launcher, with bugs concerning about flipped game screen or random crashes; it just goes to say how very limited Android GPUs are.

We can safely assume most shaders would probably run under Vulkan (with the `zink` renderer) while our own zink can't still achieve native performance, that's why we unlisted it in the list of renderers. You can add it back if you like.

Short answer or a TLDR: no.

**Comment by GaucovyAero** [comment]
Answered, closing.

**Comment by abhishekgi** [comment]
> We infamously know that Shader Support is **very** unstable. Even the most common PC shaders won't even run on PojavLauncher
> 
> VirGL; at this very moment, isn't even stable for the launcher, with bugs concerning about flipped game screen or random crashes; it just goes to say how very limited Android GPUs are.
> 
> We can safely assume most shaders would probably run under Vulkan (with the `zink` renderer) while our own zink can't still achieve native performance, that's why we unlisted it in the list of renderers. You can add it back if you like.
> 
> Short answer or a TLDR: no.

How can we add Zink back
