### ISSUE TITLE
[F-Req] Allow native "Touchscreen Mode"

### ISSUE THREAD

**Issue by yxx10** [PojavLauncherTeam/PojavLauncher#3859]
### Is this request related to a bug?

Uhh...not exactly, I think so.

### Describe the request.

So basically, Minecraft has a native _Touchscreen Mode_ that allows the use of the UI with touch input, as long as your device supports it. This is useful when dragging items around in the inventory, for example. However, you can't use this mode on Pojav (well it kind of makes sense, I guess), where it could be very useful, and far more convenient.

### Anything else?

I'm honestly not sure of how the native _Touchscreen Mode_ works internally, so maybe there's a good reason why it can't be used inside Pojav.

**Comment by Mathias-Boulay** [comment]
To be honest, I don't ever recall seeing this feature working on my friend's PC.
This might be a neat addition, still

**Comment by yxx10** [comment]
> To be honest, I don't ever recall seeing this feature working on my friend's PC.
> This might be a neat addition, still

Well that makes sense, I literally discovered yesterday how it actually worked. But yeah, it would be cool to take advantage of that feature.

**Comment by Felix14-v2** [comment]
Touch input has been fixed in https://github.com/PojavLauncherTeam/PojavLauncher/pull/5322/commits/05260575226a9dad43f1022ca4cf5aa378007f38:

https://github.com/PojavLauncherTeam/PojavLauncher/assets/75726196/b87bab1d-bb2a-44b8-b610-4483717481f9

You can [download](https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/8577708633) the build from actions and test it

**Comment by artdeell** [comment]
Fixed in latest action builds
