### ISSUE TITLE
[BUG] The material package shows two items wrong.

### ISSUE THREAD

**Issue by Baobuchi** [PojavLauncherTeam/PojavLauncher#3866]
### Describe the bug

After loading the material package, the sword and cloud are missing pixels and dislocated

### The log file and images/videos

![Screenshot_20230121_230016_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/100058929/213872908-e7d75cbd-64e2-4ff9-9bb2-e98e9da2056c.jpg)
![Screenshot_20230121_230208_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/100058929/213872921-7c7e7e00-f6c9-4be4-9117-bf5784b91a65.jpg)

### Steps To Reproduce

```markdown
Not in the journal.
```

### Expected Behavior

I hope to fix this problem.

### Platform

```markdown
- Device model: Huawei /128G
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: dahlia-216-f0c4fef80-v3_openjdk
```

**Comment by Mathias-Boulay** [comment]
how is this supposed to look like normally ?
I can't tell anything with such a high FOV setting

**Comment by GaucovyAero** [comment]
I think you'll have to deal with this unfortunately.

**Comment by GaucovyAero** [comment]
![image](https://user-images.githubusercontent.com/85581164/214357780-ffa2d8bd-a093-496d-97c3-e6981d445c70.png)
![image](https://user-images.githubusercontent.com/85581164/214357803-1eb30488-a719-4f72-97e3-83a40ce2905b.png)


> how is this supposed to look like normally ? I can't tell anything with such a high FOV setting

Looks like the shader precision is broken or something, this was basically in the "distance bug" issue, happens on gl4es, i think the sword issue is only on Mali GPUs, since both my exynoses have this iirc

**Comment by Mathias-Boulay** [comment]
might be linked to the fact mali has no "high precision" types

**Comment by GaucovyAero** [comment]
yeah, looks like thats it
