### ISSUE TITLE
[F-Req] README.md's LWJGL build instructions still "Coming Soon"

### ISSUE THREAD

**Issue by BitBlitObviMormon** [PojavLauncherTeam/PojavLauncher#3916]
It has been over two years since it was announced that the readme will teach how to build the version of LWJGL that Pojav uses. (See edcbfbf5d4aa3d394ed3f4428ad18114d6d85778) If build instructions already exist on another repository or somewhere on the Discord server then a link would be great.

**Comment by khanhduytran0** [comment]
It is still quite messy due to how we put compatibility layer into.
Native source build is quick simple: see [workflows files](https://github.com/PojavLauncherTeam/lwjgl3/tree/androidport/.github/workflows)
Java source build, however, require you to collect necessary libraries (can be from official LWJGL build), overwrite classes with Pojav’s jre_lwjgl3glfw built files.

**Comment by Mathias-Boulay** [comment]
This would still be worth to put such information, even if a bit messy.
After all, that's would still be a starting point

**Comment by Mathias-Boulay** [comment]
@khanhduytran0 with the merge of the LWJGL PR 3.3.1, can we consider this issue resolved ?

**Comment by khanhduytran0** [comment]
I guess yeah, need to update this repo’s README to reflect the build instruction.

**Comment by Mathias-Boulay** [comment]
perhaps just link to the other repository build instructions

**Comment by Mathias-Boulay** [comment]
I added the link to the build instructions, closing the issue
