### ISSUE TITLE
[question] Can VirGl support OpenGL 4.6? 

### ISSUE THREAD

**Issue by Iarkont** [PojavLauncherTeam/PojavLauncher#4053]
### Is this request related to a bug?

I'm asking you this because of a small problem rendering shaders with VirGl: 
![Screenshot_20230319_230248_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/75908293/226206407-7d3e95e4-48f3-42d9-885d-f18766c47a87.jpg)
![Screenshot_20230319_230413_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/75908293/226206423-9c389709-e824-4e89-9a34-047d50c1ff56.jpg)

As you can see, VirGl renders shaders, but with few problems. I know it's not a computer with a video card, but I still think the problem here is in the render itself. 
What's it all about: Maybe these flaws are due to the fact that VirGl is currently running on openGl 4.3? maybe shaders need a newer version of openGl? It's just that when I ran these same shaders that are in the screenshots using zink and the kirin processor, there were no such problems. 

### Describe the request.

if there is such an opportunity, it can try to release VirGl on OpenGl 4.6. if not, okay I'll put up with it. (I don't deny the question is possibly stupid) 

### Anything else?

VirGl certainly supports a smaller shader spector than zink on mali, but it's still at least some support for shaders on adreno.

**Comment by abhishekgi** [comment]
In my opinion viral should be improved and zink must be added back because zink run most shaders without issue 
In Mali gpu and viral run most shaders without issue in Andreno gpu so if both will be available we can choose the renderer according to our gpu and developer must mention after the name of renderer that which renderer is  best for which gpu and which renderer is used to run minecraft normally,   which renderer is used to run minecraft with shaders ,  which renderer is used to run minecraft with mods,  and which renderer provide best performance,  all these things should be metioned in the settings of launcher So that the new guys don't get confused selecting renderer. 

And zink renderer must be brought back it was the best .
Using zink I was able to run most shaders in my device of Mali g72 gpu with good performance 25 - 50 fps and also touched 70 fps in the latest zink build in branch:v3_zink , but viral barely run few shaders , viral is very glitchy and it's performance is not that good rarely cross 15 fps

So developer it is my request that please brought zink back

**Comment by Vylesh** [comment]
Yes Virgl is export Opengl 4.6

**Comment by GaucovyAero** [comment]
no
