### ISSUE TITLE
[BUG] Error: Could not find or load main class net.minecraft.client.Main

### ISSUE THREAD

**Issue by Calinou** [PojavLauncherTeam/PojavLauncher#4124]
### Describe the bug

I've copied a legally acquired, unmodified copy of `<Prism Launcher path>/libraries/com/mojang/minecraft/1.19.4/minecraft-1.19.4-client.jar` to my device, but the game crashes on startup. No mods are installed. I've tried all 3 graphics backends available (Holy GL4ES, virglrenderer, ANGLE).

I may be doing something wrong, but I don't know what other kind of .jar file I'm supposed to use in this case :slightly_smiling_face: 

### The log file and images/videos

```
Info: Java arguments: [-Djava.security.policy=/data/user/0/net.kdt.pojavlaunch/security/java_sandbox.policy, -Djava.security.manager=net.sourceforge.prograde.sm.ProGradeJSM, -Xbootclasspath/a:/data/user/0/net.kdt.pojavlaunch/security/pro-grade.jar, -Djava.awt.headless=false, -Dcacio.managed.screensize=720x600, -Dcacio.font.fontmanager=sun.awt.X11FontManager, -Dcacio.font.fontscaler=sun.font.FreetypeFontScaler, -Dswing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel, -Dawt.toolkit=net.java.openjdk.cacio.ctc.CTCToolkit, -Djava.awt.graphicsenv=net.java.openjdk.cacio.ctc.CTCGraphicsEnvironment, -Xbootclasspath/p:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/ResConfHack.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar, -jar, /data/user/0/net.kdt.pojavlaunch/cache/minecraft-1.19.4-client.jar]
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2177
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~9SSIqgrqzsqEzlA6VttHvw==/net.kdt.pojavlaunch-CYZTlFw5AaB9Yd56JirEaQ==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~9SSIqgrqzsqEzlA6VttHvw==/net.kdt.pojavlaunch-CYZTlFw5AaB9Yd56JirEaQ==/lib/arm64
Added custom env: LIBGL_ES=null
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1812
Exception on logging thread:
java.io.IOException: Cannot run program "logcat": error=14, Bad address
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
	at net.kdt.pojavlaunch.utils.JREUtils$1.run(JREUtils.java:129)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.io.IOException: error=14, Bad address
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
	at java.lang.ProcessImpl.start(ProcessImpl.java:141)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 2 more

OpenJDK 64-Bit Server VM warning: 
No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
Policy policy.url.2=file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.java.policy wasn't successfully parsed. Exception message: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.java.policy (No such file or directory)
Unable to initialize policy entry: Illegal character in opaque part at index 6: file:${{java.ext.dirs}}/*

Error: Could not find or load main class net.minecraft.client.Main
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7a9b771480)
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7db62373d8)
```

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Log in to a Microsoft account, specify a client JAR file (I tried 1.19.4 and 1.17.1).
3. Start the game
```

### Expected Behavior

The game should launch successfully.

### Platform

```markdown
- Device model: Samsung Galaxy Z Fold4 (https://www.gsmarena.com/samsung_galaxy_z_fold4-11737.php)
- CPU architecture: aarch64
- Android version: 13.0
- PojavLauncher version: dahlia-740-623f7dd33-v3_openjdk from Play Store - I've also tried the CI `app-debug` build from [this CI run](https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/4672049466), but I get the same error.
```

**Comment by artdeell** [comment]
Pojav stores the client JAR in a different place than Prism (not in
libraries but in versions/<version name>/<version name>.jar

Thats why you got the error

вт, 18 апр. 2023 г., 04:44 Hugo Locurcio ***@***.***>:

**Comment by Calinou** [comment]
> Pojav stores the client JAR in a different place than Prism (not in
> libraries but in versions/<version name>/<version name>.jar
>
> Thats why you got the error

I've tried downloading 1.19.4 from the vanilla launcher on Linux, then putting `versions/1.19.4/1.19.4.jar` on my phone then installing it, but I get the same error.

**Comment by artdeell** [comment]
> > Pojav stores the client JAR in a different place than Prism (not in
> > libraries but in versions//.jar
> > Thats why you got the error
> 
> I've tried downloading 1.19.4 from the vanilla launcher on Linux, then putting `versions/1.19.4/1.19.4.jar` on my phone then installing it, but I get the same error.

This would need further investigation then. Maybe check if the class is actually in the jar?
Btw, just asking, but why are you doing this? Although this should have worked, we never really tested with it so im not sure

**Comment by Calinou** [comment]
> This would need further investigation then. Maybe check if the class is actually in the jar?

`unzip -l 1.19.4.jar` gives me this list of files:

[1.19.4_list_of_files.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11263831/1.19.4_list_of_files.txt)

> This would need further investigation then. Maybe check if the class is actually in the jar?
Btw, just asking, but why are you doing this? Although this should have worked, we never really tested with it so im not sure

What are you referring to? Do you mean I should use an older version?

**Comment by artdeell** [comment]
> > This would need further investigation then. Maybe check if the class is actually in the jar?
> > Btw, just asking, but why are you doing this? Although this should have worked, we never really tested with it so im not sure
> 
> What are you referring to? Do you mean I should use an older version?

We never tried the launcher with the user putting in the JAR by hand, so i'm not sure if i can expect it to just work

**Comment by Calinou** [comment]
> We never tried the launcher with the user putting in the JAR by hand, so i'm not sure if i can expect it to just work

Oh, I just understood now that you can change the version assigned to the default profile to `1.19.4`, and it'll download everything required (provided you're logged in, of course).

I wonder if this should be done automatically after logging in, so that you don't have to edit the profile manually to achieve this. Right now, clicking the Play button will only display a "no version set" toast. At the very least, the "Play" button could be grayed out when no version is set in the currently selected profile.

I've gotten the game to run, but I think we should improve the UI or documentation related to this :slightly_smiling_face:

**Comment by artdeell** [comment]
> At the very least, the "Play" button could be grayed out when no version is set in the currently selected profile.
Didnt do it (yet) because there is no good and reliable way to sync it
The whole "Unknown" version thing is a legacy holdout from the pre-profiles launcher

**Comment by dokizin** [comment]
> I ALSO HAVE THE PROBLEM OF "Could not find or load main class net.minecraft.client.main.Main"

**finished downloading the 1.20 update and it gave this error when starting, I don't have any mods, I've tried several configurations/all types of Drivers, (MALI, Adreno) but it simply just crashes in a loop, I've tried changing the version downloader API, does anyone have a solution?** 

Full error message: 

`--------- Start launching the game
Info: Launcher version: 1.3.6 (9941143)
Info: Architecture: arm64
Info: Device model: samsung SM-A305GT
Info: API version: 30
Info: Selected Minecraft version: 1.20
Info: Custom Java arguments: NONE
Info: Java Runtime: Internal-17
Info: Account: doki (Local)
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch.zh/cache
Added custom env: AWTSTUB_WIDTH=2340
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~ZWio9FDCq0mGvSDCutVGTg==/net.kdt.pojavlaunch.zh-3V1M-JWwiEX47yARTvelcQ==/lib/arm64
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch.zh/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch.zh/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/jli:/data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~ZWio9FDCq0mGvSDCutVGTg==/net.kdt.pojavlaunch.zh-3V1M-JWwiEX47yARTvelcQ==/lib/arm64
Added custom env: LIBGL_NOERROR=1
Added custom env: POJAV_RENDERER=gallium_panfrost
Added custom env: LIBGL_ES=2
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: AWTSTUB_HEIGHT=1080
Added custom env: MESA_LIBRARY=libOSMesa_2300d.so
--------- beginning of main

I/jrelog  (16511): dlopen libOSMesa_2300d.so success
I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libjli.so success
I/jrelog  (16511): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found

I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/server/libjvm.so success

I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libverify.so success

I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libjava.so success

I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libnet.so success

I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libnio.so success

I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libawt.so success

I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libawt_headless.so success

I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libfreetype.so success

I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libfontmanager.so success

I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libjava.so success
I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libfontmanager.so success
I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libsctp.so success
I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libnio.so success

I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libjaas.so success
I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libmanagement.so success

I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libjawt.so success

I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libjavajpeg.so success

I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libj2pkcs11.so success

I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libdt_socket.so success
I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libnet.so success
I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libawt.so success

I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/librmi.so success

I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libjimage.so success
I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libawt_headless.so success

I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libprefs.so success

I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libinstrument.so success

I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libj2gss.so success

I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libverify.so success

I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libmanagement_agent.so success

I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libjdwp.so success

I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libzip.so success

I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libfreetype.so success
I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/server/libjvm.so success
I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/server/libjsig.so success

I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libmanagement_ext.so success

I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libawt_xawt.so success

I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libmlib_image.so success

I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libjsig.so success

I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/liblcms.so success

I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libjli.so success

I/jrelog  (16511): dlopen /data/user/0/net.kdt.pojavlaunch.zh/runtimes/Internal-17/lib/libextnet.so success

I/jrelog  (16511): dlopen /data/app/~~ZWio9FDCq0mGvSDCutVGTg==/net.kdt.pojavlaunch.zh-3V1M-JWwiEX47yARTvelcQ==/lib/arm64/libopenal.so success

I/jrelog  (16511): Done processing args

I/jrelog  (16511): Found JLI lib
I/jrelog  (16511): Calling JLI_Launch

Error: Could not find or load main class net.minecraft.client.main.Main
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.main.Main`
