### ISSUE TITLE
模组无法使用。

### ISSUE THREAD

**Issue by WhiteDragonvl** [PojavLauncherTeam/PojavLauncher#4156]
### Describe the bug

装载无尽贪婪模组在进入游戏的过程中会闪退。

### The log file and images/videos

无

### Steps To Reproduce

```markdown
无
```

### Expected Behavior

无

### Platform

```markdown
- Device model: Redmi Note 7
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: LOCAL-20230501 (9939125)
```

### Anything else?

无

**Comment by artdeell** [comment]
- You did not send any log files
- You are not using a build from a version controlled repository
(if you want your own version of Pojav, `git clone` the repo, don't download the source zip)
- Please write the report in English since some things like mod names don't translate well between languages.
