### ISSUE TITLE
[F-Req] Pls Bring back Zink renderer

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#4219]
### Describe the request.

Pls Bring back the Zink renderer in the older versions it was much better rendering Java shaders with less lag.

Hope you guys add it in the next update.

**Comment by mchnjt** [comment]
no

**Comment by aaaapai** [comment]
Good idea, but they know they can render more light and shadow, so it's impossible to add back.

**Comment by mchnjt** [comment]
> Good idea, but they know they can render more light and shadow, so it's impossible to add back.

@aaaapai We didn't say it's impossible. In fact we could add it back now.

The reason why it was removed in the first place is because of its performance. Yes, it can make shaders work, but at the cost of a terrible performance.

Zink runs on Vulkan, which in the first place Vulkan should be more powerful than GLES.

**Comment by root-S7** [comment]
Minecraft does not support vulkan，it is used by Vulkan to OpenGL. It performance is not as good as "Holy GL4es".
Zink removes reason is compatibility issue.
Don't worry about light shader on your phone, OpenGL ES is too difficult

**Comment by rhjdvsgsgks** [comment]
> The reason why it was removed in the first place is because of its performance. Yes, it can make shaders work, but at the cost of a terrible performance.

it not only make shader works. but also provide higher opengl version. which means optimization mod like sodium will also able to work. with that, the performance of it is not too worse.

in fact. this is the test result on my device (a old low end qcom phone)
| fps | w/o sodium | w/ sodium |
|---|---|---|
| gl4es | 5 | version string: 150version string: 150 coreERROR: 0:30: 'switch' : Reserved word. ERROR: 0:30: 'switch' : Syntax error:  syntax error INTERNAL ERROR: no main() function! |
| angel | 4 | Enum 0x8501 is currently not supported |
| virgl | 10 | 23 |

unlike the "fast/mid/slow" label in the setting. virgl is the fastest on my device. and, i tried comparing virgl/zink in termux. the latter have 1.5x fps than former. so i think its still necessary to keep zink. even it may perform slow on some device

**Comment by mchnjt** [comment]
> it not only make shader works. but also provide higher opengl version. which means optimization mod like sodium will also able to work. with that, the performance of it is "not too worse".

![2022-07-25_00 55 44](https://github.com/PojavLauncherTeam/PojavLauncher/assets/83752061/c437d6e3-008d-41e2-bd62-0bfc0b991a6c)
Yeah?

Mod or not, the problem itself is in the **renderer**, not the way how PojavLauncher uses it. I was able to get a decent (drumroll) 8fps because ¹i was playing on an old version, ²didn't fullscreen it.

Modern, bulkier phones wouldn't say the same thing otherwise; but if you use Zink on later versions, that's where the problem occurs. Nothing can fix this but to fix the renderer itself.

**Comment by rhjdvsgsgks** [comment]
> Modern, bulkier phones wouldn't say the same thing otherwise; but if you use Zink on later versions, that's where the problem occurs. Nothing can fix this but to fix the renderer itself.

what problem will occur (crash log)? please let me (or us) know. so that no one will keep asking zink in issus anymore. or even maybe some one can find a way to fix it

**Comment by rhjdvsgsgks** [comment]
related #4242 #4246

**Comment by GaucovyAero** [comment]
added in the zink branch on github actions
