### ISSUE TITLE
[BUG] 文件选择异常

### ISSUE THREAD

**Issue by lava191810** [PojavLauncherTeam/PojavLauncher#4221]
### Describe the bug

在Runtime Manager的ADD NEW的选择页面无法选中.tar.gz文件

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11531554/latestlog.txt)

https://github.com/PojavLauncherTeam/PojavLauncher/assets/117502941/93eadc1d-acb5-46fe-ab40-3d77d9b44ce7

### Steps To Reproduce

```markdown
1.启动PojavLauncher
2.打开settings-＞Java Tweaks-＞Runtime Manager
3.在弹出的JAVA VMs窗口点击ADD NEW
```

### Expected Behavior

修复无法选择.tar.gz的问题或添加一个安装JAVA VM的打开方式

### Platform

```markdown
- Device model: HUAWEI ART AL00x
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: LOCAL-20230521
```

**Comment by artdeell** [comment]
The reasons why it cant be added are following:
- Pojav only uses XZ compression for its runtime builds, since xz compresses very good
- You can't install any runtime off the internet on pojav, since most runtimes on the internet are compiled for x86_64 architecture and glibc C library (android devices use bionic C library)
- There is no OpenJ9 port that works fine on bionic libc yet. We tried to build our own, but it crashes when running JITed code.
