### ISSUE TITLE
[F-Req] Why remove virgl renderer

### ISSUE THREAD

**Issue by pddno** [PojavLauncherTeam/PojavLauncher#4252]
### Is this request related to a bug?

I want the virgl renderer to coexist with the zink renderer, not replace the virgl renderer with the zink renderer

### Describe the request.

Let virgl renderer and zink renderer exist at the same time

### Anything else?

no

**Comment by Return0endline** [comment]
VirGL is actually really slow because most phones these days are flagship phones created after 2021, like my new Infinix Hot 20i, which is a modern phone, Modern phones cannot handle VirGL, so older phones like those from 2017 and lower are able to handle VirGL. Since modern phones handle ANGLE and Holy GL4ES renderers

**Comment by GaucovyAero** [comment]
> VirGL is actually really slow because most phones these days are flagship phones created after 2021, like my new Infinix Hot 20i, which is a modern phone, Modern phones cannot handle VirGL, so older phones like those from 2017 and lower are able to handle VirGL. Since modern phones handle ANGLE and Holy GL4ES renderers

its actually absolutely random, mostly depends on the gpu driver your phone manufacturer is using (whether virgl works without issues or not)
