### ISSUE TITLE
Please support armv8l architecture

### ISSUE THREAD

**Issue by GALACTICGAMR** [PojavLauncherTeam/PojavLauncher#4289]
### Describe the request.

Please support armv8l [32-bit] or create one for 64-bit so i can use downloaded java/jre/jdk not pojav provided

**Comment by GaucovyAero** [comment]
whats so different on the downloaded one that you dont want the default one

**Comment by artdeell** [comment]
armv8l is already supported, since armv8l is backwards compatible with armv7 which is the one we already support.

If you want to use jre/jdk not provided by pojav, tough luck, because most Java distributions on the internet for Linux ARM64 are built for GNU libc, while android uses its own, called bionic.
