### ISSUE TITLE
[BUG] No sound in forge 1.7.10

### ISSUE THREAD

**Issue by VecHunter** [PojavLauncherTeam/PojavLauncher#4373]
### Describe the bug

Previously, when I played on an older version of PoajvLauncher (dahlia-265-a9993d387-v3_openjdk), everything was fine with the sound, but now in the latest version of Pojav from github, the sound has completely disappeared from the forge 1.7.10, moreover, in the original 1.7.10 the sound works

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12060801/latestlog.txt)

### Steps To Reproduce

```markdown
1. Run the latest version of Pojav from github
2. Install this forge and run
```

### Expected Behavior

I hope they will fix it soon, but for now I will play on the old version of Pojav

### Platform

```markdown
- Device model: Xiaomi M2004J19C
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: Latest versions from github automatic build
```

**Comment by Silvigarabis** [comment]
I had a similar problem when playing forge 1.12.2, but only after adding the mod "[*Dynamic Surrounding*](https://www.curseforge.com/minecraft/mc-mods/dynamic-surroundings)".
I had this problem after updating Pojavlauncher, not before updating.

So I went and tried an older version.

The last build that tested fine is: https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/5302995768

If you try to upgrade to this version, or a newer version, the above version of the game will have no sound: https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/5303733189

I tried to check the source code and found that in the new version, Pojavlauncher will add `-Dorg.lwjgl.util.NoChecks=true` as a jvm arg when starting the game. I tried to use this parameter when using the old version of Pojavlauncher to start the game. Then it also caused the game to have no sound.

I tried to reproduce this problem on Forge 1.7.10, and got the same result, using the arg `-Dorg.lwjgl.util.NoChecks=true` to start the **Forge 1.7.10** will make the game have no sound.

So, if you add `-Dorg.lwjgl.util.NoChecks=true` to the jvm args, then starting **Forge 1.7.10**, or starting **Forge 1.12.2** with the mod [*Dynamic Surrounding*](https://www.curseforge.com/minecraft/mc-mods/dynamic-surroundings), it will make the game have no sound.
~~If this mod is not added, there will be no sound problem in forge 1.12.2. But isn't adding mods just to make yourself play more happily?~~
But since this was an issue after adding the mod, I thought I'd link to #1948

The following are the log files generated by the game during testing:
[start forge 1.17.10](https://paste.gg/p/anonymous/252202a863c843eea4fbdcd3db7b88ed)
[start forge 1.12.2 with mod](https://paste.gg/p/anonymous/4c97dbcefd6a4966840c932a2846a755)

**Comment by artdeell** [comment]
@Silvigarabis we add the NoChecks argument by default because it skips some code paths that check arguments for validity, to run the game faster. If it breaks mods, you can add `-Dorg.lwjgl.util.NoChecks=false` into the arguments to override the launcher default.

**Comment by Silvigarabis** [comment]
> @Silvigarabis we add the NoChecks argument by default because it skips some code paths that check arguments for validity, to run the game faster. If it breaks mods, you can add `-Dorg.lwjgl.util.NoChecks=false` into the arguments to override the launcher default.

Adding this parameter to the jvm parameters will have no effect, because PojavLauncher will override it, unless we directly modify the code of PojavLauncher.

**Comment by VecHunter** [comment]
> I had a similar problem when playing forge 1.12.2, but only after adding the mod "[_Dynamic Surrounding_](https://www.curseforge.com/minecraft/mc-mods/dynamic-surroundings)". I had this problem after updating Pojavlauncher, not before updating.
> 
> So I went and tried an older version.
> 
> The last build that tested fine is: https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/5302995768
> 
> If you try to upgrade to this version, or a newer version, the above version of the game will have no sound: https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/5303733189
> 
> I tried to check the source code and found that in the new version, Pojavlauncher will add `-Dorg.lwjgl.util.NoChecks=true` as a jvm arg when starting the game. I tried to use this parameter when using the old version of Pojavlauncher to start the game. Then it also caused the game to have no sound.
> 
> I tried to reproduce this problem on Forge 1.7.10, and got the same result, using the arg `-Dorg.lwjgl.util.NoChecks=true` to start the **Forge 1.7.10** will make the game have no sound.
> 
> So, if you add `-Dorg.lwjgl.util.NoChecks=true` to the jvm args, then starting **Forge 1.7.10**, or starting **Forge 1.12.2** with the mod [_Dynamic Surrounding_](https://www.curseforge.com/minecraft/mc-mods/dynamic-surroundings), it will make the game have no sound. ~If this mod is not added, there will be no sound problem in forge 1.12.2. But isn't adding mods just to make yourself play more happily?~ But since this was an issue after adding the mod, I thought I'd link to #1948
> 
> The following are the log files generated by the game during testing: [start forge 1.17.10](https://paste.gg/p/anonymous/252202a863c843eea4fbdcd3db7b88ed) [start forge 1.12.2 with mod](https://paste.gg/p/anonymous/4c97dbcefd6a4966840c932a2846a755)

I downloaded the latest version of PojavLauncher, in which you can override jvm arg `-Dorg.lwjgl.util.NoChecks=true`, set it to `false` and the sound appeared in forge! Thanks everyone for the help! 😄

**Comment by Animatoragfresh** [comment]
> @Silvigarabis we add the NoChecks argument by default because it skips some code paths that check arguments for validity, to run the game faster. If it breaks mods, you can add `-Dorg.lwjgl.util.NoChecks=false` into the arguments to override the launcher default.

how to use this and where ?

**Comment by Animatoragfresh** [comment]
No sound in pojavlauncher 1.12.2 forge
When i Play in 1.12.2 the sounds are fine but when i use mods in 1.12.2 forge the sounds not working please can someone help me

**Comment by Silvigarabis** [comment]
> > @Silvigarabis we add the NoChecks argument by default because it skips some code paths that check arguments for validity, to run the game faster. If it breaks mods, you can add `-Dorg.lwjgl.util.NoChecks=false` into the arguments to override the launcher default.
> 
> how to use this and where ?

just paste `-Dorg.lwjgl.util.NoChecks=false` into “JVM arguments” in the profile settings, then save and play

**Comment by Animatoragfresh** [comment]
> > > @Silvigarabis we add the NoChecks argument by default because it skips some code paths that check arguments for validity, to run the game faster. If it breaks mods, you can add `-Dorg.lwjgl.util.NoChecks=false` into the arguments to override the launcher default.
> > 
> > 
> > how to use this and where ?
> 
> just paste `-Dorg.lwjgl.util.NoChecks=false` into “JVM arguments” in the profile settings, then save and play

its not working 😔
