### ISSUE TITLE
PLS HELP

### ISSUE THREAD

**Issue by kedrick021** [PojavLauncherTeam/PojavLauncher#4377]
### Describe the bug

After 41minutes my game is crash

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12063426/latestlog.txt)

### Steps To Reproduce

```markdown
1. create world
2. Play for 42minute
3. Crash
```

### Expected Behavior

Not crash

### Platform

```markdown
- Device model: umidigi bison 
- CPU architecture: 64
- Android version: 10
- PojavLauncher version: latest on Google play
```

### Anything else?

Plss help

**Comment by Bel69420** [comment]
You can't use GL4ES and Create with this phone

**Comment by Bel69420** [comment]
it doesn't support

**Comment by Bel69420** [comment]
Only Snapdragon device are supported

**Comment by kedrick021** [comment]
Create? Create Mod am not using it 1.12.2 am playing

**Comment by Bel69420** [comment]
oh nvm i didn't read properly sorry

**Comment by kedrick021** [comment]
> Only Snapdragon device are supported

Create? Create Mod am not using it 1.12.2 am playing

**Comment by Bel69420** [comment]
Anyway, send latestlog.txt

**Comment by kedrick021** [comment]
> Anyway, send latestlog.txt

The latest log is on there

**Comment by Bel69420** [comment]
What mod?

**Comment by kedrick021** [comment]
> What mod?

Is on latest log all mod

**Comment by alexytomi** [comment]
Your game crashes because of flywheel

Do /flywheel backend off in a superflat world.

Your phone's GPU doesn't support Create mod on HolyGL4ES. Please use Zink.

https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/5150226270

TheJudge's Zink build can run create mod without visual bugs on non-Adreno devices. 

Note that your GPU will need VK_KHR_imageless_framebuffer and VK_KHR_timeline_semaphore to run Zink.

To check if you have it, download AIDA64 and go into Devices and scroll down.

**Comment by alexytomi** [comment]
try using virgl or zink
 https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/5150226270

Also remove AE2 it's not supported 

https://pojavlauncherteam.github.io/MODS-UNSUPPORTED.html


If that doesn't work remove the gun mod
