### ISSUE TITLE
[BUG] pojav launcher cant run forge 1.6.4

### ISSUE THREAD

**Issue by epicgamerdude2013** [PojavLauncherTeam/PojavLauncher#4455]
### Describe the bug

every time i try to run forge 1.6.4 it says "Application/Game exited with code 1, check latestlog.txt for more details." 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12281207/latestlog.txt)

### Steps To Reproduce

```markdown
1. get forge 1.6.4
2. install forge on pojav launcher
3. try to run it
4. crash
```

### Expected Behavior

i expected it to work D:

### Platform

```markdown
- Device model:Acer Chromebook 315 
- CPU architecture: dont know
- Android version: chromebook Version 114.0.5735.239 (Official Build) (64-bit)
- PojavLauncher version: [Latest Release || version 3.3.1.1_rel_20210206 ]
```

**Comment by GaucovyAero** [comment]
make sure you use [this](https://www.mediafire.com/file/x46gqv0pf2rtw02/PojavLauncher_Forge_1.3.2-1.7.2_Patchpack_v1.1.zip/file) json patch and you enter `-Dfml.ignoreInvalidMinecraftCertificates=true` into your jvm arguments.
however many 1.6.4 may not work due to mods being incompatible with pojav, if you encounter crashes, join the pojav discord server and ask for help there

**Comment by epicgamerdude2013** [comment]
> make sure you use [this](https://www.mediafire.com/file/x46gqv0pf2rtw02/PojavLauncher_Forge_1.3.2-1.7.2_Patchpack_v1.1.zip/file) json patch and you enter `-Dfml.ignoreInvalidMinecraftCertificates=true` into your jvm arguments. however many 1.6.4 may not work due to mods being incompatible with pojav, if you encounter crashes, join the pojav discord server and ask for help there

u a life saver

**Comment by GaucovyAero** [comment]
np
