### ISSUE TITLE
Please add a GUI for the installation of fabric

### ISSUE THREAD

**Issue by lzfddkd** [PojavLauncherTeam/PojavLauncher#4525]

**Comment by lzfddkd** [comment]
And I hope to see the installation progress

**Comment by bsjssjjs** [comment]
I think it's a good idea

**Comment by alexytomi** [comment]
![Screenshot_20230828_125536_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/60690056/79f88eb6-5087-4726-8cb5-9481448bba02)

![Screenshot_20230828_125650_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/60690056/3b9327e3-29ac-467b-95d4-6b61ac6f8f80)


there's already one. You don't need a GUI in the installer when it's installing because you already get to pick what options you want before the installer launches

**Comment by alexytomi** [comment]
> And I hope to see the installation progress

This isn't needed because if there's an error, the log shows it. Plus it was probably making lag cause am experiencing _significantly_ faster installs using it than using the fabric installer jar with the GUI

Like from 45 seconds to 10 seconds without the GUI

If you really wanted a GUI you could just download the installer jar from fabric's website then install the jar
