### ISSUE TITLE
[F-Req] Might I be correct that we might be able to get a pre 1.17 renderer that doesn't use openGL

### ISSUE THREAD

**Issue by kingsmen1234** [PojavLauncherTeam/PojavLauncher#4602]
### Is this request related to a bug?

I suggest that we could get a 4th renderer that is like angle but works in pre 1.17 instances, for people like me who have 0 idea how to add a new renderer 

### Describe the request.

I would like to see a 4th non openGL renderer in the renderer picker (both in the edit client and edit settings options) that can run on a pre 1.17 instance

**Comment by GaucovyAero** [comment]
there is some vulkanmod implementation in the latest github actions builds, but it isnt great and it stutters a lot (because alternate surface rendering doesnt work correctly with vulkanmod yet)

![Screenshot_20230919-080459_PojavLauncher (Minecraft_ Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/85581164/7966a198-6f41-4db8-ba2a-3d7942db255e)

there however wont be a fourth option (because the vulkanmod implementation is automatic, it doesnt require changing the renderer)
