### ISSUE TITLE
[BUG] Sodium crash in 1.20.1 0.5.0+ versions not sported 

### ISSUE THREAD

**Issue by NothingMan29** [PojavLauncherTeam/PojavLauncher#4721]
### Describe the bug

Pls fix sodium crash in the 0.5.0+ sodium versions is really help comunity

### The log file and images/videos

Not

### Steps To Reproduce

```markdown
NOT
```

### Expected Behavior

I want play sodium in 1.20.2

### Platform

```markdown
Not
```

### Anything else?

So pls fix that

**Comment by GaucovyAero** [comment]
use this
[sodium-fabric-mc1.20.2-0.5.3git.81b3e6e-dirty.jar.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/12841677/sodium-fabric-mc1.20.2-0.5.3git.81b3e6e-dirty.jar.zip)
here is the source
[sodium-fabric-mc1.20.2-0.5.3git.81b3e6e-dirty-src.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/12841676/sodium-fabric-mc1.20.2-0.5.3git.81b3e6e-dirty-src.zip)

but your log is gonna get spammed a lot and since my coding skills are ass and im too lazy to fix it, it only works on gl4es
to workaround the log spamming issues you will have to fork pojav and change the string of "no context ..." to a space or just nothing

**Comment by NothingMan29** [comment]
I need

**Comment by NothingMan29** [comment]
I need remove jar.zip  remove 'zip'?

**Comment by NothingMan29** [comment]
I can use this whit quilt?

**Comment by GaucovyAero** [comment]
> I need remove jar.zip remove 'zip'?

you extract the zip

**Comment by GaucovyAero** [comment]
> I can use this whit quilt?

probably yes

**Comment by NothingMan29** [comment]
No context in the options.txt?

**Comment by GaucovyAero** [comment]
> No context in the options.txt?

what?

**Comment by GaucovyAero** [comment]
well, if you dont understand already, i wont explain the other part but yeah, this will basically get you up and running

**Comment by NothingMan29** [comment]
U say "to workaround the log spamming issues you will have to fork pojav and change the string of "no context ..." to a space or just nothing"  whare i find no context

**Comment by NothingMan29** [comment]
I extract zip and copy mods i join game but im not see sodium setting menu

**Comment by NothingMan29** [comment]
> Eğer

Yes I don't understand

**Comment by GaucovyAero** [comment]
basically, you have to fork pojav and change the lwjgl3 repository to your repository
then, in `lwjgl3/modules/lwjgl/core/src/main/c/org_lwjgl_system_ThreadLocalUtil.c`, edit "No context is current or a function that is not available in the current context was called. Are you running essential and/or <1.13" to just nothing and run actions on your pojav repository

**Comment by GaucovyAero** [comment]
its basically something that ill struggle a bit to do so yeah, i forgot how to change lwjgl3 repository to something else
