### ISSUE TITLE
[BUG] <Short description>Minecraft throws a null pointer exception during startup.

### ISSUE THREAD

**Issue by lava191810** [PojavLauncherTeam/PojavLauncher#4732]
### Describe the bug

Game version:23w41a
Java Runtime:jre17-arm64-20230227-release - 17.0.7
Renderer ANGLE

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/12900287/latest.log)
[crash-2023-10-12_07.22.59-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12900288/crash-2023-10-12_07.22.59-client.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Run Minecraft
```

### Expected Behavior

.

### Platform

```markdown
- Device model: HUAWEI ART AL00x
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: LOCAL-20230521
```

**Comment by GaucovyAero** [comment]
your lwjgl is outdated, because your pojav version is 4 months old, thats why it doesnt work, update to the latest actions build

![Screenshot_20231014-041523_PojavLauncher (Minecraft_ Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/85581164/2657febc-cf2c-4519-bd66-6cbe42e65158)
