### ISSUE TITLE
[F-Req] when will mods be fixed

### ISSUE THREAD

**Issue by hiimabignoobwihenolive** [PojavLauncherTeam/PojavLauncher#4751]
### Is this request related to a bug?

Will be there a time where pojav can run most mods like dynamic surroundings or ambient sounds and most of the gun mods where they are fixed and some other things like modpacks and better optimisation for Minecraft?

### Describe the request.

Fixing mods and some other shit like the fact that most phones can't run 1.16+

### Anything else?

Yeah pojav is going to shit because every update that it gets it gets it breaks some shit

**Comment by GaucovyAero** [comment]
Dunno if you ever thought about it but we are basically normal people just like you, we arent anything more or less. What i mean by that is that some stuff is difficult to code and we cant do it because we dont have the knowledge and time nor money to pay someone to do it.

> Will be there a time where pojav can run most mods like dynamic surroundings or ambient sounds and most of the gun mods where they are fixed and some other things like modpacks and better optimisation for Minecraft?

a) to get dynamic surroundings to work, you would have to implement OpenGL 4.6 into gl4es, which is basically impossible afaik (mobile GPUs only run OpenGL **ES** 3.2 maximum)
b) you gotta tell the sounds mod devs to implement a software encoder (the issue is that not all stuff like libraries that exist for PC also exist for Android, e. g. PhysX)

> Fixing mods and some other shit like the fact that most phones can't run 1.16+

i have no idea where you got that from, everything should work just fine

> Yeah pojav is going to shit because every update that it gets it gets it breaks some shit

you didnt create any issues regarding it breaking stuff (and what specifically, along with logs), create a new issue and it should get fixed if it is something that worked before or is fixable
we dont have a testing team that tests if whatever mods work or not, our testing team is the playerbase
if you dont tell us that something doesnt work, there is a pretty high chance that we wont even come across the issue

**Comment by hiimabignoobwihenolive** [comment]
> Dunno if you ever thought about it but we are basically normal people just like you, we arent anything more or less. What i mean by that is that some stuff is difficult to code and we cant do it because we dont have the knowledge and time nor money to pay someone to do it.
> 
> > Will be there a time where pojav can run most mods like dynamic surroundings or ambient sounds and most of the gun mods where they are fixed and some other things like modpacks and better optimisation for Minecraft?
> 
> a) to get dynamic surroundings to work, you would have to implement OpenGL 4.6 into gl4es, which is basically impossible afaik (mobile GPUs only run OpenGL **ES** 3.2 maximum) b) you gotta tell the sounds mod devs to implement a software encoder (the issue is that not all stuff like libraries that exist for PC also exist for Android, e. g. PhysX)
> 
> > Fixing mods and some other shit like the fact that most phones can't run 1.16+
> 
> i have no idea where you got that from, everything should work just fine
> 
> > Yeah pojav is going to shit because every update that it gets it gets it breaks some shit
> 
> you didnt create any issues regarding it breaking stuff (and what specifically, along with logs), create a new issue and it should get fixed if it is something that worked before or is fixable we dont have a testing team that tests if whatever mods work or not, our testing team is the playerbase if you dont tell us that something doesnt work, there is a pretty high chance that we wont even come across the issue

Im sorry i was just asking if they would get fixed and i cannot ask in the discord if they will get fixed or not because I don't have a phone number so i am sorry and also most of the issues that i am experiencing are from my old ass phone so its not your problem or the dev team problem ( i am soo sorry i won't do it again)

**Comment by GaucovyAero** [comment]
sorry for scaring you out, if you have issues running 1.17+ or anything like that, please send the log here and i will help you out and reopen the issue
