### ISSUE TITLE
New update

### ISSUE THREAD

**Issue by kjjjjjjjjjjjj** [PojavLauncherTeam/PojavLauncher#4799]
### Is this request related to a bug?

I need new update with a fixing George who fix Java who fix modepack who fix everything even forge installer I have a this feature request and we need a new update to in lower device

### Describe the request.

Fixing jar who fix every bug

### Anything else?

We want update fast

**Comment by GaucovyAero** [comment]
invalid

**Comment by kjjjjjjjjjjjj** [comment]
I will say to Pojavlauncher official create not you

**Comment by mchnjt** [comment]
> I will say to Pojavlauncher official create not you

I hope you know who you're talking to.

**Comment by kjjjjjjjjjjjj** [comment]
I am telling to GaucovyAero

**Comment by mchnjt** [comment]
> I am telling to GaucovyAero

It looks like you're blind. No offense, but we don't even know what you're talking about. If it's a severe issue, then we can tell the developers to see what's the exact issue that's causing this. But for matters like this, you're not a priority if it's not a severe issue. Please try fixing yourself. Learn how to do that and don't rush to our repository just because you're having troubles on making a specific feature work on your expectations.

**Comment by GaucovyAero** [comment]
i finally understand what you meant by that but as you can probably see, no other minecraft launcher does that because its too difficult to implement, same goes for gl4es on opengl 3.2
