### ISSUE TITLE
Things to improve

### ISSUE THREAD

**Issue by franta279** [PojavLauncherTeam/PojavLauncher#4927]
### Describe the bug

Pojav Launcher is awasome app. Its well optimized, good fps etc. However here are some things to improve. First: I am not able to edit minecraft folder like mods, resourcepacks etc. becouse Samsung dont let me there. So it would be nice to able move minecraft folder to place that is accesable by everyone. Second: soemtimes happend that shift key is lagged an I have to push it again. Third: I tryed to use pojav launcher with samsung DEX. Mouse is in this mode unusuble... I hope you can fix it!

### The log file and images/videos

![Screenshot_20231206_151736_My Files](https://github.com/PojavLauncherTeam/PojavLauncher/assets/124684376/154e619e-f9b1-45c3-bcd3-22ebccd7b1c3)

### Steps To Reproduce

```markdown
you tell me
```

### Expected Behavior

....

### Platform

```markdown
Samsung galaxy tab S9+
```

**Comment by GaucovyAero** [comment]
1. that would be a security issue, use mixplorer or zarchiver to access the directory: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/
2. duplicate issue, not fixable yet as nobody knows where the issue is coming from and is not consistent to reproduce
3. nobody of the devs has a samsung device with dex support, therefore dex support will likely not come any soon
