### ISSUE TITLE
[F-Req] minecraft.jar mods

### ISSUE THREAD

**Issue by kin-fuyuki** [PojavLauncherTeam/PojavLauncher#5038]
### Describe the request.

there are some mods that are made directly to the minecraft jar, either adding to it or modifying it.

multimc/prism have a feature you can replace the jar file, or add to the minecraft jar file.

this is needed for who plays on old modded versions like the now popular better than adventure and not so secret saturday

### Anything else?

also please create a option where u can disable automatic .json and .jar update

**Comment by GaucovyAero** [comment]
here is the link, as stock BTA does not work on Pojav because of a missing LWJGL method
https://www.neb.cx/posts/1.7.7.x-on-pojavlauncher/

this link might also be useful for installing jarmods that are not BTA and do work out of the box (e. g. Optimine b1.1_02), it shows you how to disable the jar updating, and the json itself wont update when you change the `id`
https://pojavlauncherteam.github.io/CUSTOM-MC.html
^ for this guide i suggest using RAR instead of MiX to modify the jar, as MiX might corrupt it
