### ISSUE TITLE
Lots of memory

### ISSUE THREAD

**Issue by Bielgg13** [PojavLauncherTeam/PojavLauncher#5084]
### Describe the bug

The application is consuming a lot of RAM memory,It uses so much memory that it fights for memory with the system and ends up crashing the app due to lack of RAM

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14017050/latestlog.txt)

### Steps To Reproduce

```markdown
Crash
```

### Expected Behavior

I hope the app consumes less RAM 

### Platform

```markdown
- Device model: POCO X5 5g
- CPU architecture: ARM CORTEX-A78
- Android version: 13
- PojavLauncher version: edelweiss-20240119-acd356d-feat/touch_event_refactor
```

**Comment by itsMeRaj69** [comment]
Even I'm facing the same issue

**Comment by alexytomi** [comment]
Logs don't mention it crashing because of a lack of RAM. 

Also that's just how Minecraft works. You can install mods that try to optimize RAM usage (i.e Lithium, ModernFix, FerriteCore) but ultimately, Minecraft is a RAM hog. It's not "fixable"

Anyways your actual issue is that you're trying to run mods that can't keep up with your phone and the server can't keep up. Get a better phone.

**Comment by GaucovyAero** [comment]
i mean yeah if you are using a bunch of mods, its kinda obvious that its going to take a lot of memory, same thing would happen on a PC
