### ISSUE TITLE
[BUG] 1.20.2 Fabric Black Screen

### ISSUE THREAD

**Issue by 3geETR** [PojavLauncherTeam/PojavLauncher#5143]
### Describe the bug

Hello, I installed fabric, but when I try to open it, it stays on a black screen. I looked at the logs, I think it cannot access the file (I'm not sure). I open it with Java 17.  I can open 1.20.2 in vanilla.I give all file premissions

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14228417/latestlog.txt)

### Steps To Reproduce

```markdown
1. I installed pojav launcher and opened it.
2. I installed vanilla 1.20.2
3. I installed fabric 1.20.2 with fabric installer
4. I run the fabric 1.20.2
```

### Expected Behavior

How do I run fabric 1.20.2 without any problems?

### Platform

```markdown
- Device model: Samsung Galaxy Note 5
- CPU architecture: arm64
- Android version: 7.0
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
fabric wont work if you are on android 9 and lower because of android permission issues
your phone does allow installing an [unofficial build of lineageos 17.1 (android 10)](https://xdaforums.com/t/rom-unofficial-10-0-11-28-2022-lineageos-17-1-s6-s6edge-s6edge-note5.4132641/), so you might aswell give it a try
