### ISSUE TITLE
[BUG] The game becomes buggy when using Zink Render on Samsung S22 (Minecraft 1.20.4 with Optifine)

### ISSUE THREAD

**Issue by Emylian-bit** [PojavLauncherTeam/PojavLauncher#5180]
### Describe the bug

The textures become glitched and messy when using Zink Render. I use a Samsung S22 with Exynos 2200 
![Screenshot_20240228_133501_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/81913214/d50f7d2f-d8c9-4ab5-9e0b-d4dde20b9756)

### The log file and images/videos

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/14433520/latest.log)

### Steps To Reproduce

```markdown
1. Start Pojav Launcher
2. Choose Zink Renderer
3. Play Minecraft 1.20.4 with Optifine
```

### Expected Behavior

I expected zink to display correctly instead of this buggy mess

### Platform

```markdown
- Device model: Samsung S22
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by Bel69420** [comment]
This is known issue, it seems like Xclipse has driver issue that cause zink to be like this.

**Comment by Bel69420** [comment]
I'm afraid pojav devs can't fix this as they're not creating this renderer.

**Comment by Bel69420** [comment]
Maybe ask Mesa

**Comment by Emylian-bit** [comment]
> Maybe ask Mesa

Sorry for interrupting but who is Mesa and how can I fix this?

**Comment by Bel69420** [comment]
> > Maybe ask Mesa
> 
> Sorry for interrupting but who is Mesa and how can I fix this?

They're not a person. Mesa3D graphics Library is a library of open-source implementations of various graphics APIs such as OpenGL, OpenGL ES, Vulkan, etc.

PojavLauncher relyies on their Zink gallium driver to provide wide OpenGL compatibility coverage to OpenGL ES devices that PojavLauncher users commonly use. 

However this comes with certain drawbacks. If the phone you try to use it on has broken/incompatible Vulkan drivers, it csn result in lots of bugs. This is why HolyGL4ES is another option. 

HolyGL4ES isn't developed by mesa3d though, it's developed by the PojavLauncherTeam. However due to the limitations of OpenGL ES, it can only implement a fraction of OpenGL 3.0 + whatever the public repository from ptitseb has.

However that's straying quite a bit off topic. Point being, PojavLauncherTeam cannot fix this. It's Samsung's fault for shoehorning AMD RDNA 2 into a mobile chip then slapping ANGLE on it.

**Comment by Bel69420** [comment]
I mean, ask zink developer for Xclipse fix

**Comment by alexytomi** [comment]
> I mean, ask zink developer for Xclipse fix

The zink developer _is_ mesa3dlibrary

Go PR it yourself :)
