### ISSUE TITLE
[F-Req] Ability to swap right click to left click when tapping on screen

### ISSUE THREAD

**Issue by DarthKebab** [PojavLauncherTeam/PojavLauncher#5341]
### Describe the request.

So basically when you tap the screen it right clicks and you have to hold it to left click (I am aware you can change the hold time needed). Is there any way to reverse this so when you tap the screen it left clicks and when you hold the screen it right clicks?

**Comment by grosioso** [comment]
sorry for bad english (if i HAD any) but you can easily do that in-game because there's no need to ask

take a look at this:

![Screenshot_20240411-180809_PojavLauncher (Minecraft Java Edition for Android).png](https://github.com/PojavLauncherTeam/PojavLauncher/assets/166200108/c3c5c5a2-927e-4b9a-8e16-59be5a5ffeca)

if you swap those controls, it will work:

![Screenshot_20240411-180820_PojavLauncher (Minecraft Java Edition for Android).png](https://github.com/PojavLauncherTeam/PojavLauncher/assets/166200108/89fd65ec-a602-4a79-a7af-157a9bd6b5f9)

how?
on the first section, press the SEC button and that will change into "Button 2". then the third section will turn into "Button 1" if you press the PRI button.

Button 1 = the PRI button
Button 2 = the SEC button

hope that helps!

**Comment by grosioso** [comment]
just try it, it works pretty well

**Comment by GaucovyAero** [comment]
lmao i didnt even think about this, cool
