### ISSUE TITLE
do not Remove the ability to download Minecraft on Local accounts

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#5564]
### Describe the request.

Use pojav should be free for all of us. just people want premium account or can use Microsoft account need to register or login in Microsoft

### Anything else?

Pojav launcher is famous for frist best launcher for run minecraft on android and free to use. YouTubers says not me

**Comment by zhangxixi2012** [comment]
Very supportive!!!!!

**Comment by frdude** [comment]
Even if they do, what's stopping users from using a modified version of the launcher to play on local accounts? There is no way to solve piracy, there's always a way to pirate stuff.
My opinion: keep the launcher as is, changing this won't make much of a difference.

**Comment by Marshall2439** [comment]
Its dumb because even tho buying minecraft you're supporting evil company that it microsoft, you still need to support devs too. Not to mention that you cant play online servers aswell. Its not that easy to let it free for us because if it was possible minecraft itself would have been free 30 dollars is not that much of a price (unless developing country like me)
