### ISSUE TITLE
[F-Req] New Version(#5745) Un liked changement 

### ISSUE THREAD

**Issue by TeomanOFF** [PojavLauncherTeam/PojavLauncher#5750]
### Is this request related to a bug?

It is not related to a bug

### Describe the request.

My request is to remove the Microsoft account check for players that have no internet connections and has only has internet limited for only having the apk then creating a local account to have internet and for people that doesn't belive in the security of pojav (like my case where i own minecraft but i don't wanna put my Microsoft account) 

### Anything else?

i don't have any other problem to explain

**Comment by MovTery** [comment]
@TeomanOFF That is just a merge request; it hasn't actually updated to PojavLauncher. There's no need to worry about it.

**Comment by MovTery** [comment]
Regarding the security issue you mentioned, rest assured, I've reviewed the source code of PojavLauncher and confirmed that it does not pose any account security risks. What you should really care about is what versions you use with your account. The official version is certainly trustworthy. Be cautious of unofficial versions and mods—before installing and using them, make sure they come from reputable sources. Otherwise, they could potentially threaten your account security.

**Comment by TeomanOFF** [comment]
> @TeomanOFF That is just a merge request; it hasn't actually updated to PojavLauncher. There's no need to worry about it.

so it will not be in the next release?

**Comment by kiokori-git** [comment]
> > @TeomanOFF That is just a merge request; it hasn't actually updated to PojavLauncher. There's no need to worry about it.
> 
> so it will not be in the next release?

it will not be

**Comment by TeomanOFF** [comment]
> > > @TeomanOFF That is just a merge request; it hasn't actually updated to PojavLauncher. There's no need to worry about it.
> > 
> > 
> > so it will not be in the next release?
> 
> it will not be

So pojavlauncher secretly allow cracked players? (not my case)

**Comment by ghost** [comment]
Probably
