### ISSUE TITLE
[BUG] Sodium 1.21 now can playable?

### ISSUE THREAD

**Issue by SpeedCuberMC** [PojavLauncherTeam/PojavLauncher#5891]
### Describe the bug

Sodium 1.21 now can playable because last update says added LWJGL 3.3.3

### The log file and images/videos

Nothing

### Steps To Reproduce

```markdown
Nothing
```

### Expected Behavior

Nothing

### Platform

```markdown
- Device model:.
- CPU architecture:.
- Android version:. 
- PojavLauncher version:.
```

### Anything else?

Nothing

**Comment by khanhduytran0** [comment]
LWJGL update has nothing to do with Sodium compatibility. Whether or not it is playable depends on your device GPU and available drivers, mainly OpenGL capabilities.
Also, guess what… due to a breaking change in LWJGL, Sodium for older versions explicitly require LWJGL 3.3.1, making it super annoying to deal with. It’s either we gotta make a LWJGL switcher for this or whatnot.
