### ISSUE TITLE
24w34a+ black screen

### ISSUE THREAD

**Issue by KedisPL** [PojavLauncherTeam/PojavLauncher#5968]
### Describe the bug

Snapshot 24w34a has a black screen when launched (rendering broken).

### The log file and images/videos

![latestlog.txt](https://github.com/user-attachments/files/16733263/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Launch 24w34a
```

### Expected Behavior

Screen should render

### Platform

```markdown
- Device model: Infinix Note 12 Pro 5G
- CPU architecture: arm
- Android version: 13
- PojavLauncher version: latest v3_openjdk from Actions
```

**Comment by GaucovyAero** [comment]
turn on the shader dump and send latestlog.txt, not latest.log

**Comment by KedisPL** [comment]
I can't because for some reason I have ACCESS_DENIED

**Comment by KedisPL** [comment]
Also this seems to be an issue on Holy GL4ES, but Zink doesn't work on my device and ANGLE is so laggy.

**Comment by ghost** [comment]
Where I can find the shader dump file log
 .
 .
 .
 .
![Screenshot_2024-08-22-22-04-58-657_ru zdevs zarchiver-edit](https://github.com/user-attachments/assets/a7236cff-1717-4a7b-b707-b52f1766c972)

**Comment by ghost** [comment]
> I can't because for some reason I have ACCESS_DENIED

Be Sure zarchiver is connected to shizuku and turn on USB debugging and wireless debugging

**Comment by GaucovyAero** [comment]
> I can't because for some reason I have ACCESS_DENIED

you can also use the share log file button and get the file from where you share it

**Comment by KedisPL** [comment]
> > I can't because for some reason I have ACCESS_DENIED
> 
> you can also use the share log file button and get the file from where you share it

Still the same problem

**Comment by KedisPL** [comment]
> > I can't because for some reason I have ACCESS_DENIED
> 
> Be Sure zarchiver is connected to shizuku and turn on USB debugging and wireless debugging

It didn't do anything either

**Comment by GaucovyAero** [comment]
> Still the same problem

same way you got latest.log you should get latestlog.txt, its 2 directories back

**Comment by kasrarouhi** [comment]
> Where I can find the shader dump file log . . . . ![Screenshot_2024-08-22-22-04-58-657_ru zdevs zarchiver-edit](https://private-user-images.githubusercontent.com/140465266/360589704-a7236cff-1717-4a7b-b707-b52f1766c972.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNjA1NTIsIm5iZiI6MTcyNDM2MDI1MiwicGF0aCI6Ii8xNDA0NjUyNjYvMzYwNTg5NzA0LWE3MjM2Y2ZmLTE3MTctNGE3Yi1iNzA3LWI1MmYxNzY2Yzk3Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMlQyMDU3MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03N2Y0ZmYxNWNhNzVlODFiNDE0YjJjMzY3NjJlY2U0N2JjYjBmNjhmYWE0NWQ2Y2RiYmZhZjJhOTg5NTM3YTJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-ed99njflhOjdkJs0-w84fc6jAcPQUPd1JAMGvqmiiA)

I didn't get my answer

**Comment by ghost** [comment]
I don't know shader dump related to latestlog.txt but I turned on shader dumping with holygl4es renderer and there is

[latestlog.txt](https://github.com/user-attachments/files/16719572/latestlog.txt)

**Comment by KedisPL** [comment]
> > Still the same problem
> 
> same way you got latest.log you should get latestlog.txt, its 2 directories back

Yes, I know but this file is somehow locked ![Screenshot_20240823-081307.jpg](https://github.com/user-attachments/assets/b81da409-628e-4dfb-bf9a-64aee53b1be1)

**Comment by ghost** [comment]
> > > Still the same problem
> > 
> > 
> > same way you got latest.log you should get latestlog.txt, its 2 directories back
> 
> Yes, I know but this file is somehow locked ![Screenshot_20240823-081307.jpg](https://private-user-images.githubusercontent.com/79972336/360811043-b81da409-628e-4dfb-bf9a-64aee53b1be1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MDQ3NjUsIm5iZiI6MTcyNDQwNDQ2NSwicGF0aCI6Ii83OTk3MjMzNi8zNjA4MTEwNDMtYjgxZGE0MDktNjI4ZS00ZGZiLWJmOWEtNjRhZWU1M2IxYmUxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDA5MTQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0NmZjNDc4MWU1NDVmMmQ3MjdmYjdmNzdmYjE4YTQ4NGY1YTUxOWFmMDcyYTVhMjI2NTBhZTdlZTliYmFhZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cgolt_8D--9JeWZ9gIFVtxXZCdNP_b-KjGUvZAToKiI)

Copy the latesrlog.txt file in downloads folder and try again

**Comment by KedisPL** [comment]
> > > > Still the same problem
> > > 
> > > 
> > > same way you got latest.log you should get latestlog.txt, its 2 directories back
> > 
> > 
> > Yes, I know but this file is somehow locked ![Screenshot_20240823-081307.jpg](https://private-user-images.githubusercontent.com/79972336/360811043-b81da409-628e-4dfb-bf9a-64aee53b1be1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MDQ3NjUsIm5iZiI6MTcyNDQwNDQ2NSwicGF0aCI6Ii83OTk3MjMzNi8zNjA4MTEwNDMtYjgxZGE0MDktNjI4ZS00ZGZiLWJmOWEtNjRhZWU1M2IxYmUxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDA5MTQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0NmZjNDc4MWU1NDVmMmQ3MjdmYjdmNzdmYjE4YTQ4NGY1YTUxOWFmMDcyYTVhMjI2NTBhZTdlZTliYmFhZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cgolt_8D--9JeWZ9gIFVtxXZCdNP_b-KjGUvZAToKiI)
> 
> Copy the latesrlog.txt file in downloads folder and try again

When I try to copy an error pops up and the file is empty

**Comment by GaucovyAero** [comment]
thats the first phone that has ever had this issue

**Comment by ghost** [comment]
> > > > > Still the same problem
> > > > 
> > > > 
> > > > same way you got latest.log you should get latestlog.txt, its 2 directories back
> > > 
> > > 
> > > Yes, I know but this file is somehow locked ![Screenshot_20240823-081307.jpg](https://private-user-images.githubusercontent.com/79972336/360811043-b81da409-628e-4dfb-bf9a-64aee53b1be1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MDQ3NjUsIm5iZiI6MTcyNDQwNDQ2NSwicGF0aCI6Ii83OTk3MjMzNi8zNjA4MTEwNDMtYjgxZGE0MDktNjI4ZS00ZGZiLWJmOWEtNjRhZWU1M2IxYmUxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDA5MTQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0NmZjNDc4MWU1NDVmMmQ3MjdmYjdmNzdmYjE4YTQ4NGY1YTUxOWFmMDcyYTVhMjI2NTBhZTdlZTliYmFhZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cgolt_8D--9JeWZ9gIFVtxXZCdNP_b-KjGUvZAToKiI)
> > 
> > 
> > Copy the latesrlog.txt file in downloads folder and try again
> 
> When I try to copy an error pops up and the file is empty

Don't know

**Comment by GaucovyAero** [comment]
try using a different file manager, maybe mixplorer? free download mixplorer.com

**Comment by KedisPL** [comment]
> try using a different file manager, maybe mixplorer? free download mixplorer.com

Also not working. A message pops up: Not possible

**Comment by KedisPL** [comment]
After deleting the file and restarting the game, the file got unlocked.

**Comment by KedisPL** [comment]
![latestlog.txt](https://github.com/user-attachments/files/16730665/latestlog.txt)

**Comment by GaucovyAero** [comment]
you did not turn on the shader dump

**Comment by KedisPL** [comment]
![latestlog.txt](https://github.com/user-attachments/files/16733263/latestlog.txt)

**Comment by GaucovyAero** [comment]
good

**Comment by ghost** [comment]
Why. you said it's good

**Comment by GStudiosX2** [comment]
Yeah I also had this issue on HolyGL4ES it also seemed to not work on 1.21.1 as well? Switching to ANGLE fixed it my phone doesn't support zink 

Edit: nvm I might have opened the wrong version i think it only affects 24w34a I thought it was broken on 1.21.1 forge but it looks like I just didn't wait long enough

**Comment by GStudiosX2** [comment]
oh seems like it is broken on 1.21.1 forge only though ![Screenshot_20240826-041034.png](https://github.com/user-attachments/assets/0270517c-7977-449f-b4b7-75be3ed439ff)

**Comment by kasrarouhi** [comment]
> Yeah I also had this issue on HolyGL4ES it also seemed to not work on 1.21.1 as well? Switching to ANGLE fixed it my phone doesn't support zink
> 
> Edit: nvm I might have opened the wrong version i think it only affects 24w34a I thought it was broken on 1.21.1 forge but it looks like I just didn't wait long enough

Yes it's just for snapshot 24w34a not other versions and i agree about the time

**Comment by Marshall2439** [comment]
just when is update with newer gles dropping out smh. Angle is giving me bad performance because of scamsung

**Comment by Jimhasaburger** [comment]
I have this issue on my Samsung galaxy a50

**Comment by Emoji03258** [comment]
<log4j:Event logger="ac" timestamp="1727860967346" level="WARN" thread="main">
    <log4j:Message><![CDATA[Failed retrieving info for group processor]]></log4j:Message>
    <log4j:Throwable><![CDATA[java.lang.Error: 

There is an incompatible JNA native library installed on this system
Expected: 7.0.0
Found:    6.1.6
(at /data/app/net.kdt.pojavlaunch-ptXox3H5zB1fChRZariMZg==/lib/arm64/libjnidispatch.so).
To resolve this issue you may do one of the following:
 - remove or uninstall the offending library
 - set the system property jna.nosys=true
 - set jna.boot.library.path to include the path to the version of the 
   jnidispatch library included with the JNA jar file you are using

	at com.sun.jna.Native.<clinit>(Native.java:230)
	at com.sun.jna.platform.linux.Udev.<clinit>(Udev.java:37)
	at oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:80)
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:171)
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:67)
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:58)
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:43)
	at oshi.util.Memoizer$1.get(Memoizer.java:61)
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:48)
	at ac.c(SourceFile:79)
	at ac.a(SourceFile:87)
	at ac.a(SourceFile:79)
	at ac.e(SourceFile:56)
	at ac.a(SourceFile:87)
	at ac.<init>(SourceFile:56)
	at o.<init>(SourceFile:35)
	at o.g(SourceFile:234)
	at net.minecraft.client.main.Main.main(SourceFile:133)
]]></log4j:Throwable>
  </log4j:Event>
  <log4j:Event logger="ac" timestamp="1727860967482" level="WARN" thread="main">
    <log4j:Message><![CDATA[Failed retrieving info for group memory]]></log4j:Message>
    <log4j:Throwable><![CDATA[java.lang.NoClassDefFoundError: Could not initialize class oshi.software.os.linux.LinuxOperatingSystem
	at oshi.hardware.platform.linux.LinuxGlobalMemory.<clinit>(LinuxGlobalMemory.java:28)
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createMemory(LinuxHardwareAbstractionLayer.java:38)
	at oshi.util.Memoizer$1.get(Memoizer.java:61)
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getMemory(AbstractHardwareAbstractionLayer.java:60)
	at ac.a(SourceFile:81)
	at ac.a(SourceFile:87)
	at ac.a(SourceFile:81)
	at ac.e(SourceFile:56)
	at ac.a(SourceFile:87)
	at ac.<init>(SourceFile:56)
	at o.<init>(SourceFile:35)
	at o.g(SourceFile:234)
	at net.minecraft.client.main.Main.main(SourceFile:133)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.Error: 

There is an incompatible JNA native library installed on this system
Expected: 7.0.0
Found:    6.1.6
(at /data/app/net.kdt.pojavlaunch-ptXox3H5zB1fChRZariMZg==/lib/arm64/libjnidispatch.so).
To resolve this issue you may do one of the following:
 - remove or uninstall the offending library
 - set the system property jna.nosys=true
 - set jna.boot.library.path to include the path to the version of the 
   jnidispatch library included with the JNA jar file you are using
 [in thread "main"]
	at com.sun.jna.Native.<clinit>(Native.java:230)
	at com.sun.jna.platform.linux.Udev.<clinit>(Udev.java:37)
	at oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:80)
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:171)
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:67)
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:58)
	at oshi.hardware.platform.linux.LinuxHar
dwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:43)
	at oshi.util.Memoizer$1.get(Memoizer.java:61)
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:48)
	at ac.c(SourceFile:79)
	at ac.a(SourceFile:87)
	at ac.a(SourceFile:79)
	... 6 more
]]></log4j:Throwable>
  </log4j:Event>
  <log4j:Event logger="com.mojang.datafixers.DataFixerBuilder" timestamp="1727860969802" level="INFO" thread="Datafixer Bootstrap">
    <log4j:Message><![CDATA[234 Datafixer optimizations took 2785 milliseconds]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="alq" timestamp="1727861003849" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[[STDERR]: [LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.]]></log4j:Message>
  </log4j:Event>
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
  <log4j:Event logger="com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService" timestamp="1727861005618" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="fke" timestamp="1727861005749" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[Setting user: Axololt2839]]></log4j:Message>
  </log4j:Event>
Registered forkAndExec
  <log4j:Event logger="fki" timestamp="1727861006695" level="ERROR" thread="Render thread">
    <log4j:Message><![CDATA[Error parsing option value off for option Fullscreen: Not a boolean: "off"]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="fke" timestamp="1727861006819" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[Backend library: LWJGL version 3.3.3-snapshot]]></log4j:Message>
  </log4j:Event>
EGLBridge: Binding to OpenGL ES
  <log4j:Event logger="alq" timestamp="1727861007071" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[[STDERR]: [LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.]]></log4j:Message>
  </log4j:Event>
Initialising gl4es
v1.1.5 built on Jul 14 2024 19:34:14
Using GLES 2.0 backend
loaded: libGLESv2.so
loaded: libEGL.so
Using GLES 2.0 backend
Hardware Full NPOT detected and used
Extension GL_EXT_blend_minmax  detected and used
Extension GL_EXT_draw_buffers  detected and used
FBO are in core, and so used
PointSprite are in core, and so used
CubeMap are in core, and so used
BlendColor is in core, and so used
Blend Subtract is in core, and so used
Blend Function and Equation Separation is in core, and so used
Texture Mirrored Repeat is in core, and so used
Extension GL_OES_mapbuffer  detected
Extension GL_OES_element_index_uint  detected and used
Extension GL_OES_packed_depth_stencil  detected and used
Extension GL_OES_depth24  detected and used
Extension GL_OES_rgb8_rgba8  detected and used
Extension GL_EXT_multi_draw_arrays  detected
Extension GL_EXT_texture_format_BGRA8888  detected and used
Extension GL_OES_depth_texture  detected and used
Extension GL_OES_texture_stencil8  detected and used
Extension GL_EXT_texture_rg  detected and used
Extension GL_OES_texture_float  detected and used
Extension GL_OES_texture_half_float  detected and used
Extension GL_EXT_color_buffer_float  detected and used
Extension GL_EXT_color_buffer_half_float  detected and used
Extension GL_OES_fragment_precision_high  detected and used
Extension GL_EXT_shader_texture_lod detected and used
Max vertex attrib: 16
Extension GL_OES_standard_derivatives  detected and used
Extension GL_OES_get_program_binary  detected and used
Number of supported Program Binary Format: 1
Max texture size: 4096
Max Varying Vector: 15
Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
Extension GL_EXT_texture_filter_anisotropic  detected and used
Max Anisotropic filtering: 2
Hardware vendor is Imagination Technologies
GLSL 300 es supported
GLSL 310 es supported and used
GLSL 320 es supported
Max Color Attachments: 8 / Draw buffers: 8
EGLImage to Texture2D supported
EGLImage to RenderBuffer supported
ignore MipMap
glGetError() always return GL_NOERROR
Targeting OpenGL 2.1
No hack in shader converter to define overloaded function with int
Not trying to batch small subsequent glDrawXXXX
try to use VBO
FBO workaround for using binded texture enabled
Force texture for Attachment color0 on FBO
Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
Force normals to be normalized on FPE shaders
glX Will try to recycle EGL Surface
Current folder is:/storage/emulated/0/games/PojavLauncher/.minecraft
  <log4j:Event logger="fke" timestamp="1727861008320" level="ERROR" thread="Download-2">
    <log4j:Message><![CDATA[Failed to fetch user properties]]></log4j:Message>
    <log4j:Throwable><![CDATA[com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:59)
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:150)
	at fke.bM(SourceFile:464)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: MinecraftClientHttpException[type=HTTP_ERROR, status=401, response=ErrorResponse[path=/player/attributes, error=null, errorMessage=null, details=null]]
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:100)
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:57)
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:121)
	... 5 more
]]></log4j:Throwable>
  </log4j:Event>
  <log4j:Event logger="alq" timestamp="1727861008478" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[[STDERR]: [LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="alq" timestamp="1727861009302" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[[STDERR]: [LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="com.mojang.text2speech.Narrator" timestamp="1727861011992" level="ERROR" thread="Render thread">
    <log4j:Message><![CDATA[Error while loading the narrator]]></log4j:Message>
    <log4j:Throwable><![CDATA[com.mojang.text2speech.Narrator$InitializeException: Failed to load library flite
	at com.mojang.text2speech.NarratorLinux$FliteLibrary.loadNative(NarratorLinux.java:69)
	at com.mojang.text2speech.NarratorLinux.<init>(NarratorLinux.java:18)
	at com.mojang.text2speech.Narrator.getNarrator(Narrator.java:41)
	at fjv.<init>(SourceFile:19)
	at fke.<init>(SourceFile:701)
	at net.minecraft.client.main.Main.main(SourceFile:248)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
	at com.sun.jna.NativeLibrary.<clinit>(NativeLibrary.java:90)
	at com.mojang.text2speech.NarratorLinux$FliteLibrary.loadNative(NarratorLinux.java:67)
	... 5 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.Error: 

There is an incompatible JNA native library installed on this system
Expected: 7.0.0
Found:    6.1.6
(at /data/app/net.kdt.pojavlaunch-ptXox3H5zB1fChRZariMZg==/lib/arm64/libjnidispatch.so).
To resolve this issue you may do one of the following:
 - remove or uninstall the offending library
 - set the system property jna.nosys=true
 - set jna.boot.library.path to include the path to the version of the 
   jnidispatch library included with the JNA jar file you are using
 [in thread "main"]
	at com.sun.jna.Native.<clinit>(Native.java:230)
	at com.sun.jna.platform.linux.Udev.<clinit>(Udev.java:37)
	at oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:80)
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:171)
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:67)
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:58)
	at oshi.hardware.platform.linux.LinuxHardwareAbstractio
nLayer.createProcessor(LinuxHardwareAbstractionLayer.java:43)
	at oshi.util.Memoizer$1.get(Memoizer.java:61)
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:48)
	at ac.c(SourceFile:79)
	at ac.a(SourceFile:87)
	at ac.a(SourceFile:79)
	at ac.e(SourceFile:56)
	at ac.a(SourceFile:87)
	at ac.<init>(SourceFile:56)
	at o.<init>(SourceFile:35)
	at o.g(SourceFile:234)
	at net.minecraft.client.main.Main.main(SourceFile:133)
]]></log4j:Throwable>
  </log4j:Event>
  <log4j:Event logger="ava" timestamp="1727861012177" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[Reloading ResourceManager: vanilla]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="fpl" timestamp="1727861012839" level="INFO" thread="Worker-Main-5">
    <log4j:Message><![CDATA[Found unifont_all_no_pua-15.1.05.hex, loading]]></log4j:Message>
  </log4j:Event>
I/NativeInput( 1952): Input ready: 1

  <log4j:Event logger="fpl" timestamp="1727861015095" level="INFO" thread="Worker-Main-3">
    <log4j:Message><![CDATA[Found unifont_jp_patch-15.1.05.hex, loading]]></log4j:Message>
  </log4j:Event>
--------- beginning of system

The latest versions (SnapShot 24w34a - ...)

**Comment by GaucovyAero** [comment]
use LTW for now in the latest actions builds

**Comment by KedisPL** [comment]
Where can I enable LTW because I can't find it anywhere (I have the latest version installed)

**Comment by kasrarouhi** [comment]
![Screenshot_2024-10-27-19-45-27-861_com android chrome~2](https://github.com/user-attachments/assets/36b07c6d-d476-4549-b5b4-8c113701f26f)

**Comment by ghost** [comment]
![Screenshot_2024-10-30-05-34-52-840_com android chrome-edit](https://github.com/user-attachments/assets/800142d2-7936-478f-b925-70805f38e41b)

**Comment by KedisPL** [comment]
oh, thanks
