### ISSUE TITLE
[F-Req] Add libsqlitejdbc.so

### ISSUE THREAD

**Issue by Dilen0001** [PojavLauncherTeam/PojavLauncher#5995]
### Is this request related to a bug?

Distant Horizon Mod Doesn't Work Without libsqlitejdbc.so

### Describe the request.

Add libsqlitejdbc.so to the Pojav Launcher Application so that the Distant Horizon Mod can run

### Anything else?

There isn't any

**Comment by GaucovyAero** [comment]
Distant Horizons for android:
- Download the modified jre archive provided here
 - Verify that the name of the downloaded archive matches the one listed here.  If it doesn't, rename the archive to make it match.
- Import the jre into pojav by pressing:
"Settings icon button > Java tweaks > Runtime Manager > ADD NEW", then go to your downloads folder and select "jre21-arm64-SQLite.tar.xz"
- Open the settings of an instance which has DH installed in, select "Java Runtime" and then "jre21 arm64 SQLite"

Due to various bugs and performance issues, it's not recommended to use this mod.

https://cdn.discordapp.com/attachments/824307242533781514/1249069976778707034/jre21-arm64-SQLite.tar.xz?ex=66d0c011&is=66cf6e91&hm=6a9da8846f65f32de704b03149ebc9cf3d9e07bda522748bfea17688aa5e8d5e&
