### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by RaiBreno** [PojavLauncherTeam/PojavLauncher#6083]
### Describe the bug

Por favor consertem isso eu quero logo a minha conta do pojavlauncher (Please fix this I want my pojavlauncher account now)

### The log file and images/videos

Ysnskjdmdjxmz

### Steps To Reproduce

```markdown
Hshshshzjmx
```

### Expected Behavior

Eu pensei que ia funcionar o login (I thought the login would work)

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

Erro de entrar na conta (Error logging into account)

**Comment by GaucovyAero** [comment]
to fix your login issues, log into minecraft.net, sometimes just logging into the site fixes the issue, but check these things:

a) you must own minecraft java edition
b) you must have a username set (check this if you are using Xbox Game Pass)
c) your account should not be classified as a child member of a family, otherwise it might not work
d) if the error is different and links you somewhere, try following the steps there
