### ISSUE TITLE
[DEV BUILD] Distance horizon still cause crash.

### ISSUE THREAD

**Issue by TylerHaoNhot** [PojavLauncherTeam/PojavLauncher#6139]
### Describe the bug

As i heard about the new render that it's support Distance horizon, I throw myself to try it out. But unfortunately it's still crashing with -1 error code.

### The log file and images/videos

new dev build:
![Screenshot_2024-10-05-09-26-25-976_io github pyoncord app-edit](https://github.com/user-attachments/assets/891a8012-6498-4ec0-bd50-c5c029fb9873)

version:
![IMG_20241005_120145](https://github.com/user-attachments/assets/d9dc4a2a-97ae-4f19-a0c8-d2ac2776a023)

code -1:
![Screenshot_2024-10-05-12-08-59-252_net kdt pojavlaunch debug](https://github.com/user-attachments/assets/94dd849e-ed33-4b01-bf78-f290deb80f04)

lastest log:
[latestlog.txt](https://github.com/user-attachments/files/17265240/latestlog.txt)

### Steps To Reproduce

```markdown
1 Download pojav launcher dev build from github.
2 move my mods from normal pojav to the dev ones.
3 install distance horizon
4 select the new render
5 enter the game
6 disable fog, cloud in DH settings
7 enter world
8 crash.
```

### Expected Behavior

fix this problem

### Platform

```markdown
- Device model: redmi k20 pro
- CPU architecture: arm 64
- Android version: 11
- PojavLauncher version: dev build (picture section, i can't copy text)
```

**Comment by TylerHaoNhot** [comment]
notice: I use DH combine with sodium. donno if it's work properly.
mod files:
[i gotta compress DH into a different file because the file size is too large lol.zip](https://github.com/user-attachments/files/17265255/i.gotta.compress.DH.into.a.different.file.because.the.file.size.is.too.large.lol.zip)
[mods.zip](https://github.com/user-attachments/files/17265257/mods.zip)

**Comment by CowSheep72** [comment]
how much chunks did you allocate

**Comment by CowSheep72** [comment]
how many chunks did you allocate

**Comment by GaucovyAero** [comment]
you have to use a custom jre for this i think

Distant Horizons for Android:
- Download the modified jre archive provided here
 - Verify that the name of the downloaded archive matches the one listed here.  If it doesn't, rename the archive to make it match.
- Import the jre into pojav by pressing:
"Settings icon button > Java tweaks > Runtime Manager > ADD NEW", then go to your downloads folder and select "jre21-arm64-SQLite.tar.xz"
- Open the settings of an instance which has DH installed in, select "Java Runtime" and then "jre21 arm64 SQLite"

Due to various bugs and performance issues, it's not recommended to use this mod.

https://www.mediafire.com/file/1nb671wnfoabb3n/jre21-arm64-SQLite.tar.xz/file
