### ISSUE TITLE
[BUG] the red screen problem show how to fix it in 1.21.3 

### ISSUE THREAD

**Issue by bolrom** [PojavLauncherTeam/PojavLauncher#6230]
### Describe the bug

I no use keyboard 

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/17609900/latestlog.txt

### Steps To Reproduce

```markdown
Give me pis
```

### Expected Behavior

I am not use keyboard and mouse 

### Platform

```markdown
- Device model: MAI132
- CPU architecture: Octa-core Max 1.40GHz
- Android version: 7
- PojavLauncher version: foxglove-20240922-6a6a29-v3_openjdk
```

### Anything else?

Pis fix this i try all render but no work

**Comment by bolrom** [comment]
Pis fix

**Comment by Yoidiotiamback** [comment]
Did you use ltw renderer and check?

**Comment by bolrom** [comment]
I use all but not working 😕

**Comment by Putul182** [comment]
Same problem with me

**Comment by Putul182** [comment]
Plz fixed it

**Comment by Yoidiotiamback** [comment]
Go to github actions scroll down and you will see add renderer, add compatible check click it download go to game renderer select LTW if you this should 100% work if not use zink still does not work you have to wait until a new workflow releases from github go download it check if it works if your problem fixed with ltw them leave

**Comment by bolrom** [comment]
Give me detailed video pis
