### ISSUE TITLE
Pojavlauncher fatal error *application game exited with code 6 pojav launcher*

### ISSUE THREAD

**Issue by Kolya872** [PojavLauncherTeam/PojavLauncher#6325]
### Is this request related to a bug?

I play on version 1.20.6 with mods on f a b r i c .
![Screenshot_2024-11-29-21-45-59-091_net kdt pojavlaunch](https://github.com/user-attachments/assets/50a604ea-5e5a-4bcc-afbb-5b65e0759d30)

### Describe the request.

I play on version 1.20.6 with mods on f a b r i c .

### Anything else?

I play on version 1.20.6 with mods on f a b r i c .

**Comment by CodeByAnvith** [comment]
same issue here , did u find  a fix?

**Comment by CodeByAnvith** [comment]
i found a fix use haste modpack from modrinth it will work

**Comment by JustAMinecraftplayer** [comment]
Did you use Sodium or Vulkan Mod? They are not supported with pojav launcher yet. Sodium only works with LTW renderer. You also need Open GL ES 3.1 supported for sodium to work with LTW. For me the LTW renderer only works with sodium installed.

**Comment by Marshall2439** [comment]
I'd recommend this to be a bug and not a feature request (because enhancement label smh)
Also pls consider sharing log file

**Comment by CamoWolf1222** [comment]
there seems to be a fix in #6377

**Comment by GaucovyAero** [comment]
no log provided

**Comment by pojavuserisneedhelp** [comment]
--------- Starting game with Launcher Debug!
Info: Launcher version: gladiolus-20250118-c04e3af-v3_openjdk
Info: Architecture: arm64
Info: Device model: INFINIX MOBILITY LIMITED Infinix X6812B
Info: API version: 30
Info: Selected Minecraft version: fabric-loader-0.16.10-1.21.4
Info: Custom Java arguments: ""
--------- beginning of main

Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2460
Added custom env: FORCE_VSYNC=true
Added custom env: POJAV_NATIVEDIR=/data/app/~~pky6mzNPkkjIl-OT1OiLIw==/net.kdt.pojavlaunch-Yy_1OKmLC2kv8Kq82u0eig==/lib/arm64
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: POJAV_VSYNC_IN_ZINK=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~pky6mzNPkkjIl-OT1OiLIw==/net.kdt.pojavlaunch-Yy_1OKmLC2kv8Kq82u0eig==/lib/arm64
Added custom env: LIBGL_NOERROR=1
Added custom env: POJAV_RENDERER=opengles3_ltw
Added custom env: LIBGL_ES=3
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: POJAVEXEC_EGL=libltw.so
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: AWTSTUB_HEIGHT=1080
I/jrelog  ( 3625): dlopen libltw.so success
I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjli.so success
I/jrelog  ( 3625): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found

I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/server/libjvm.so success

I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libverify.so success

I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjava.so success

I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libnet.so success

I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libnio.so success

I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libawt.so success

I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libawt_headless.so success

I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libfreetype.so success

I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libfontmanager.so success

I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libzip.so success
I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libsctp.so success

I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjawt.so success
I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libawt.so success

I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjimage.so success

I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libmanagement.so success

I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/librmi.so success

I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libmanagement_agent.so success
I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/server/libjvm.so success

I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/server/libjsig.so success
I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/liblcms.so success

I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libmanagement_ext.so success

I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjsig.so success

I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libdt_socket.so success
I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libnet.so success

I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjli.so success
I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libfreetype.so success
I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libawt_headless.so success

I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjdwp.so success

I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libsyslookup.so success

I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjavajpeg.so success

I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libmlib_image.so success

I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libinstrument.so success

I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libfontmanager.so success
I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libverify.so success
I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libj2pkcs11.so success

I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjaas.so success

I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libextnet.so success

I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libprefs.so success
I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjava.so success
I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libnio.so success

I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libj2gss.so success
I/jrelog  ( 3625): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libawt_xawt.so success

I/jrelog  ( 3625): dlopen /data/app/~~pky6mzNPkkjIl-OT1OiLIw==/net.kdt.pojavlaunch-Yy_1OKmLC2kv8Kq82u0eig==/lib/arm64/libopenal.so success

I/jrelog  ( 3625): Done processing args

I/jrelog  ( 3625): Found JLI lib
I/jrelog  ( 3625): Calling JLI_Launch

java.lang.UnsupportedOperationException
	at java.base/java.lang.invoke.VarForm.getMemberName(VarForm.java:118)
	at com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader.makeNonFinal(CTCPreloadClassLoader.java:125)
	at com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader.<clinit>(CTCPreloadClassLoader.java:70)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:200)
	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at java.base/java.lang.ClassLoader.initSystemClassLoader(ClassLoader.java:2012)
	at java.base/java.lang.System.initPhase3(System.java:2329)
  <log4j:Event logger="FabricLoader/GameProvider" timestamp="1740588512495" level="INFO" thread="main">
    <log4j:Message><![CDATA[Loading Minecraft 1.21.4 with Fabric Loader 0.16.10]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="FabricLoader/Resolution" timestamp="1740588513141" level="WARN" thread="main">
    <log4j:Message><![CDATA[Warnings were found!
 - Mod 'Slotted Armor HUD' (slotted_armor_hud) 1.2.5 recommends version 15.0.127 or later of cloth-config2, which is missing!
	 - You should install version 15.0.127 or later of cloth-config2 for the optimal experience.]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="FabricLoader" timestamp="1740588513147" level="INFO" thread="main">
    <log4j:Message><![CDATA[Loading 57 mods:
	- fabric-api 0.118.0+1.21.4
	   |-- fabric-api-base 0.4.54+b47eab6b04
	   |-- fabric-api-lookup-api-v1 1.6.86+b1caf1e904
	   |-- fabric-biome-api-v1 15.0.6+b1c29d8e04
	   |-- fabric-block-api-v1 1.0.31+7feeb73304
	   |-- fabric-block-view-api-v2 1.0.19+7feeb73304
	   |-- fabric-blockrenderlayer-v1 2.0.8+7feeb73304
	   |-- fabric-client-tags-api-v1 1.1.29+20ea1e2304
	   |-- fabric-command-api-v1 1.2.62+f71b366f04
	   |-- fabric-command-api-v2 2.2.41+e496eb1504
	   |-- fabric-commands-v0 0.2.79+df3654b304
	   |-- fabric-content-registries-v0 9.1.19+25d1a67604
	   |-- fabric-convention-tags-v1 2.1.17+7f945d5b04
	   |-- fabric-convention-tags-v2 2.13.0+360374ac04
	   |-- fabric-crash-report-info-v1 0.3.6+7feeb73304
	   |-- fabric-data-attachment-api-v1 1.6.0+4e7c604904
	   |-- fabric-data-generation-api-v1 22.2.12+60b6f1b704
	   |-- fabric-dimensions-v1 4.0.10+7feeb73304
	   |-- fabric-entity-events-v1 2.0.14+da99546b04
	   |-- fabric-events-interaction-v0 4.0.3+a4eebcf004
	   |-- fabric-game-rule-api-v1 1.0.63+7d48d43904
	   |-- fabric-item-api-v1 11.3.0+ee91fa1f04
	   |-- fabric-item-group-api-v1 4.2.2+fcb9601404
	   |-- fabric-key-binding-api-v1 1.0.57+7d48d43904
	   |-- fabric-keybindings-v0 0.2.55+df3654b304
	   |-- fabric-lifecycle-events-v1 2.5.4+bf2a60eb04
	   |-- fabric-loot-api-v2 3.0.38+3f89f5a504
	   |-- fabric-loot-api-v3 1.0.26+203e6b2304
	   |-- fabric-message-api-v1 6.0.25+7feeb73304
	   |-- fabric-model-loading-api-v1 4.3.0+ae23723504
	   |-- fabric-networking-api-v1 4.3.10+8998135104
	   |-- fabric-object-builder-api-v1 18.0.13+7d48d43904
	   |-- fabric-particles-v1 4.0.14+7feeb73304
	   |-- fabric-recipe-api-v1 8.1.0+640e77ae04
	   |-- fabric-registry-sync-v0 6.1.9+360374ac04
	   |-- fabric-renderer-api-v1 5.0.3+50f0feb204
	   |-- fabric-renderer-indigo 2.0.3+50f0feb204
	   |-- fabric-rendering-data-attachment-v1 0.3.57+73761d2e04
	   |-- fabric-rendering-fluids-v1 3.1.19+7feeb73304
	   |-- fabric-rendering-v1 10.2.1+0d31b09f04
	   |-- fabric-resource-conditions-api-v1 5.0.13+203e6b2304
	   |-- fabric-resource-loader-v0 3.1.1+360374ac04
	   |-- fabric-screen-api-v1 2.0.38+7feeb73304
	   |-- fabric-screen-handler-api-v1 1.3.116+7feeb73304
	   |-- fabric-sound-api-v1 1.0.32+7feeb73304
	   |-- fabric-tag-api-v1 1.0.7+7d48d43904
	   |-- fabric-transfer-api-v1 5.4.9+efa825c904
	   \-- fabric-transitive-access-wideners-v1 6.3.2+56e78b9b04
	- fabricloader 0.16.10
	   \-- mixinextras 0.4.1
	- fullbright 2.0.1
	- java 21
	- minecraft 1.21.4
	- modmenu 13.0.2
	   \-- placeholder-api 2.5.1+1.21.3
	- slotted_armor_hud 1.2.5
	- yet_another_config_lib_v3 3.6.3+1.21.4-fabric]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="FabricLoader" timestamp="1740588513149" level="WARN" thread="main">
    <log4j:Message><![CDATA[Found 1 non-fabric mod:
	- OptiFine_1.21.4_HD_U_J3.jar]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="FabricLoader/Mixin" timestamp="1740588513507" level="INFO" thread="main">
    <log4j:Message><![CDATA[SpongePowered MIXIN Subsystem Version=0.8.7 Source=file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/fabricmc/sponge-mixin/0.15.4+mixin.0.8.7/sponge-mixin-0.15.4+mixin.0.8.7.jar Service=Knot/Fabric Env=CLIENT]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="FabricLoader/Mixin" timestamp="1740588513761" level="INFO" thread="main">
    <log4j:Message><![CDATA[Compatibility level set to JAVA_21]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="FabricLoader/Mixin" timestamp="1740588516398" level="WARN" thread="main">
    <log4j:Message><![CDATA[Error loading class: org/jetbrains/annotations/ApiStatus$Internal (java.lang.ClassNotFoundException: org/jetbrains/annotations/ApiStatus$Internal)]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="FabricLoader/MixinExtras|Service" timestamp="1740588518520" level="INFO" thread="main">
    <log4j:Message><![CDATA[Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.4.1).]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="net.minecraft.class_6396" timestamp="1740588521737" level="WARN" thread="main">
    <log4j:Message><![CDATA[Failed retrieving info for group processor]]></log4j:Message>
    <log4j:Throwable><![CDATA[java.lang.Error: 

There is an incompatible JNA native library installed on this system
Expected: 7.0.2
Found:    6.1.6
(at /data/app/~~pky6mzNPkkjIl-OT1OiLIw==/net.kdt.pojavlaunch-Yy_1OKmLC2kv8Kq82u0eig==/lib/arm64/libjnidispatch.so).
To resolve this issue you may do one of the following:
 - remove or uninstall the offending library
 - set the system property jna.nosys=true
 - set jna.boot.library.path to include the path to the version of the 
   jnidispatch library included with the JNA jar file you are using

	at knot//com.sun.jna.Native.<clinit>(Native.java:230)
	at knot//com.sun.jna.platform.linux.Udev.<clinit>(Udev.java:37)
	at knot//oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:86)
	at knot//oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:174)
	at knot//oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:68)
	at knot//oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:59)
	at knot//oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:43)
	at knot//oshi.util.Memoizer$1.get(Memoizer.java:61)
	at knot//oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:48)
	at knot//net.minecraft.class_6396.method_37146(class_6396.java:79)
	at knot//net.minecraft.class_6396.method_37121(class_6396.java:87)
	at knot//net.minecraft.class_6396.method_37128(class_6396.java:79)
	at knot//net.minecraft.class_6396.method_37143(class_6396.java:56)
	at knot//net.minecraft.class_6396.method_37121(class_6396.java:87)
	at knot//net.minecraft.class_6396.<init>(class_6396.java:56)
	at knot//net.minecraft.class_128.<init>(class_128.java:35)
	at knot//net.minecraft.class_128.method_24305(class_128.java:234)
	at knot//net.minecraft.client.main.Main.main(Main.java:134)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
]]></log4j:Throwable>
  </log4j:Event>
  <log4j:Event logger="net.minecraft.class_6396" timestamp="1740588521983" level="WARN" thread="main">
    <log4j:Message><![CDATA[Failed retrieving info for group memory]]></log4j:Message>
    <log4j:Throwable><![CDATA[java.lang.NoClassDefFoundError: Could not initialize class oshi.software.os.linux.LinuxOperatingSystem
	at knot//oshi.hardware.platform.linux.LinuxGlobalMemory.<clinit>(LinuxGlobalMemory.java:28)
	at knot//oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createMemory(LinuxHardwareAbstractionLayer.java:38)
	at knot//oshi.util.Memoizer$1.get(Memoizer.java:61)
	at knot//oshi.hardware.common.AbstractHardwareAbstractionLayer.getMemory(AbstractHardwareAbstractionLayer.java:60)
	at knot//net.minecraft.class_6396.method_37133(class_6396.java:81)
	at knot//net.minecraft.class_6396.method_37121(class_6396.java:87)
	at knot//net.minecraft.class_6396.method_37128(class_6396.java:81)
	at knot//net.minecraft.class_6396.method_37143(class_6396.java:56)
	at knot//net.minecraft.class_6396.method_37121(class_6396.java:87)
	at knot//net.minecraft.class_6396.<init>(class_6396.java:56)
	at knot//net.minecraft.class_128.<init>(class_128.java:35)
	at knot//net.minecraft.class_128.method_24305(class_128.java:234)
	at knot//net.minecraft.client.main.Main.main(Main.java:134)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.Error: 

There is an incompatible JNA native library installed on this system
Expected: 7.0.2
Found:    6.1.6
(at /data/app/~~pky6mzNPkkjIl-OT1OiLIw==/net.kdt.pojavlaunch-Yy_1OKmLC2kv8Kq82u0eig==/lib/arm64/libjnidispatch.so).
To resolve this issue you may do one of the following:
 - remove or uninstall the offending library
 - set the system property jna.nosys=true
 - set jna.boot.library.path to include the path to the version of the 
   jnidispatch library included with the JNA jar file you are using
 [in thread "main"]
	at knot//com.sun.jna.Native.<clinit>(Native.java:230)
	at knot//com.sun.jna.platform.linux.Udev.<clinit>(Udev.java:37)
	at knot//oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:86)
	at knot//oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:174)
	at knot//oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:68)
	at knot//oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:59)
	at knot//oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:43)
	at knot//oshi.util.Memoizer$1.get(Memoizer.java:61)
	at knot//oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:48)
	at knot//net.minecraft.class_6396.method_37146(class_6396.java:79)
	at knot//net.minecraft.class_6396.method_37121(class_6396.java:87)
	at knot//net.minecraft.class_6396.method_37128(class_6396.java:79)
	... 9 more
]]></log4j:Throwable>
  </log4j:Event>
  <log4j:Event logger="com.mojang.datafixers.DataFixerBuilder" timestamp="1740588523973" level="INFO" thread="Datafixer Bootstrap">
    <log4j:Message><![CDATA[243 Datafixer optimizations took 2610 milliseconds]]></log4j:Message>
  </log4j:Event>
--------- beginning of system

  <log4j:Event logger="net.minecraft.class_2983" timestamp="1740588542512" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[[STDERR]: [LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.]]></log4j:Message>
  </log4j:Event>
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better di

**Comment by pojavuserisneedhelp** [comment]
Can anyone help me with this

**Comment by pojavuserisneedhelp** [comment]
I just wanna play on a server and it won't let me

**Comment by nomily** [comment]
I had the same error using cobblemon modpack (includes sodium). 

Fixed it by setting the renderer to LTW and adding `-Djna.nosys=false` in the JVM arguments section. This removed the error in every version of the modpack (I tried 1.20.1 and 1.21.1 for cobblemon modpack).

I'm not sure if this fix will work with other mods, but I hope this helps

**Comment by ItzMeBramz** [comment]
I just downloaded the version and haven't installed any mods but suddenly it's like this. Please does anyone know how to fix it?

**Comment by ItzMeBramz** [comment]
aku i can't add file
