### ISSUE TITLE
[BUG] crashing when shader is activated

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#6362]
### Describe the bug

Whenever I activate a shader on 1.8.9/other versions its crashing

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/18050855/latestlog.txt)

### Steps To Reproduce

```markdown
1. Open pojav launcher
2. Select 1.8.9(optifine)
3. Open a world
4. Activate a shader
```

### Expected Behavior

Get shader working without crashing

### Platform

```markdown
- Device model: Realme 6 8/128
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: foxglove-20241124-a5d02c1-v3_openjdk.
```

**Comment by system32crowdstrikewin11** [comment]
First of all by seeing your latest log it seems like you are using Holy renderer
![Screenshot_2024-12-11-23-56-59-400_ru zdevs zarchiver-edit](https://github.com/user-attachments/assets/9adf1ea3-95a1-4f8a-b3c1-726e368b25c4)
So make sure you select the zink renderer if the zink renderer doesn't works and crashes then 
Try using pojav edelweiss version 
It works as of my knowledge this issue is arising because of mesa 24 comparability issues that mesa 24 brought to mali GPUs either it runs with visual glitches or the game crashes or you are maybe using

**Comment by ghost** [comment]
@system32crowdstrikewin11  the edelweiss version is working fine. also i got another issue too so i play with external keyboard and mouse and keyboard works fine and mouse too but mouse is only working for moving the screen and the buttons is not working when i click on left,right click the screen will stucked and when i un-release the click its fine

**Comment by GaucovyAero** [comment]
the mouse handling is fixed in foxglove i think

**Comment by GaucovyAero** [comment]
also, that specific mouse issue is only on realme devices

**Comment by ghost** [comment]
ohh ok thanks
