### ISSUE TITLE
Travis builds for instant beta testing.

### ISSUE THREAD

**Issue by artdeell** [PojavLauncherTeam/PojavLauncher#8]
I know a good idea: setup Travis CI bulds and tests for PojavLauncher, so betas can be builded and tested instantly.
This will add some useful features like:
  > Testing right after new commit.
  > Easy deployment.
  > Builds will not require PC.

**Comment by khanhduytran0** [comment]
#### I didn't create in Android Studio. I'm not often use PC, current I using AIDE. Since AIDE use legacy files, it will takes some times to move from AIDE to Android Studio. Setup will be after I move to Android Studio. I have some questions:
- Preview/Release builds I've signed with my keystore file. How can I setup to automatically sign or just with debug key?
- How to edit code without JIT, IDE and my own testing?

**Comment by artdeell** [comment]
Hm. Travis builds can be easily ruled via configs, so you can write anything you want in scripts.

**Comment by artdeell** [comment]
Code can be edited directly from GitHub's editor. You can use Android client like OpenHub.

**Comment by khanhduytran0** [comment]
It's hard for debugging, if use normal text editor, I need debug by my brain.

**Comment by khanhduytran0** [comment]
So push via an IDE will be better.
